# Conclusion et Discussion {-}

## Bilan des travaux {-}
En mobilisant le Baromètre d’opinion de la Drees, nous avons construit un espace social de la pauvreté mobilisant trois dimensions largement citées dans la littérature (chapitre \@ref(chap1)) : 

1. La pauvreté monétaire, indicateur phare et traditionnel d’étude des inégalités ; 

2. La pauvreté institutionnelle, c’est-à-dire bénéficier ou non de prestations sociales et être en situation d’assistance vis-à-vis de l’Etat. 
3. La pauvreté subjective, c’est-à-dire des indicateurs focalisés sur le ressenti des individus. Deux indicateurs du Baromètre d’opinion ont été mobilisés dans notre étude : le sentiment de pauvreté (indiquer se sentir pauvre) et les difficultés financières perçues (indiquer disposer d’un revenu inférieur au revenu minimum que l’on juge nécessaire pour vivre convenablement).


Cette dimension subjective a été étudiée en profondeur dès le chapitre \@ref(nonreducnv), prolongeant l’étude de @duvoux2018qui. Nous avons constaté à notre tour que, même si le niveau de vie explique fortement ces indicateurs de pauvreté subjective, la pauvreté institutionnelle joue également un grand rôle à niveau de vie fixé. Par ailleurs, certains groupes sociaux se sentent particulièrement pauvres toutes choses étant égales par ailleurs : les locataires, les personnes en dehors du marché du travail (et les ouvriers et employés dans une moindre mesure) et les ménages composés d’un seul adulte (familles monoparentales et personnes vivant seules). 

Dans le but de connaître les interactions entre les trois dimensions de la pauvreté évoquées précédemment, nous avons proposé dans le chapitre \@ref(esexplo) une démarche englobante de construction de l’espace social de la pauvreté. Nous avons utilisé pour cela deux méthodes. Une Analyse des Correspondances Multiples (ACM) a tout d’abord montré que les différentes dimensions sont fortement corrélées et amènent à la construction par Classification Ascendante Hiérarchique (CAH) de cinq classes ordonnées de pauvreté. Puis, une Analyse en Facteurs communs Exploratoire (AFE), modélisant les dimensions comme des variables latentes, a ajouté de la nuance en démontrant que les dimensions de la pauvreté sont non seulement théoriquement construites mais également empiriquement validées. Les indicateurs de pauvreté institutionnelle, directement en lien avec les politiques publiques de lutte contre la précarité, se rassemblent en effet en une même dimension latente. Parmi les personnes appartenant aux classes moyennes, certains profils sont plus susceptibles de percevoir des prestations sociales : les jeunes, les locataires, les inactifs et les ménages avec enfants (d’un ou deux adultes). Ce sont ces mêmes ménages qui se sentent le moins en difficulté financière à niveau de revenu fixé. En outre, la forte corrélation entre difficultés financières réelles et perçues valide la pertinence des indicateurs de pauvreté subjective comme compléments aux indicateurs objectifs. 

En guise de synthèse de ce mémoire de recherche, le chapitre \@ref(esconfi)  propose une méthodologie synthétique amenant à elle seule à des résultats semblables à ceux obtenus avec les multiples méthodes des chapitres \@ref(nonreducnv) et \@ref(esexplo) : l’Analyse en Facteurs communs Confirmatoire (AFC). L’indice synthétique de pauvreté construit par cette méthode montre que l’éloignement du marché du travail et l’appartenance à une famille monoparentale accentuent fortement les chances d’être pauvre, toutes dimensions confondues. En outre, l’analyse des dimensions prises une à une montre que le poids du subjectif est relativement faible chez ces populations pourtant particulièrement pauvres. En revanche, chez les personnes vivant seules sans enfant et les ouvriers, la pauvreté subjective est particulièrement élevée comparativement à leur niveau de pauvreté objective. Chez les plus jeunes et les ménages avec enfants, la situation y est opposée avec un niveau de pauvreté subjectif relativement faible. 

## Discussions et prolongements envisageables {-}

L’utilisation combinée d’un Baromètre d’opinion et de méthodes en variables latentes a ainsi permis d’étudier sous un angle relativement original l’espace social de la pauvreté en France. Nous axerons donc la discussion qui ponctue ce mémoire d’une part sur les données et d’autre part sur les méthodes utilisées. 

S’agissant des données, la principale force du Baromètre d’opinion de la Drees est de proposer une mesure directe de la pauvreté via le sentiment de pauvreté, même si, comme le souligne @lahieyte2020sociologie, cet indicateur comporte de nombreux biais potentiels liés à la formulation de la question (question relativement imprécise, posée dans un contexte particulier) et à l’interaction avec l’enquêteur (gêne potentielle de se déclarer pauvre qui s’illustre par un taux de non-réponse à la question relativement élevé ).

Il serait possible d’aller encore plus loin dans la mobilisation des données subjectives du Baromètre en creusant grâce à d’autres parties du questionnaire ce que révèle réellement le sentiment de pauvreté au-delà du manque de ressources monétaires. Les Français y sont en effet interrogés sur leur optimisme face à l’avenir et sur leur vision sur l’évolution passée et à venir des inégalités, de la pauvreté et l’exclusion. Ces différents éléments peuvent approcher une certaine notion d’insécurité sociale. On les interroge également sur la manière dont ils considèrent leur situation actuelle et sur leur sentiment ou non d’avoir une moins bonne situation que leur parent au même âge (déclassement intergénérationnel), ce qui pourrait permettre de faire ressortir la notion d’infériorité sociale. Enfin, un certain nombre de questions posées dans le cadre d’un module ponctuel en 2018 permettraient d’élargir le prisme de la pauvreté ressentie : penser pouvoir compter sur quelqu’un en cas d’un grave problème personnel, avoir du mal à boucler ses fins de mois, avoir des revenus variables d’un mois sur l’autre, penser pouvoir faire face à une dépense imprévue, ou encore être inquiet de ne pas pouvoir être soigné en cas d’un grave problème de santé. On pourrait analyser si chacun de ces indicateurs se distingue (comme le sentiment de pauvreté) ou non (comme les difficultés financières perçues) de la dimension monétaire.

Des données alternatives au Baromètre d’opinion pourraient également être utilisées, par exemple les données du dispositif SRCV  (ou *European Union Statistics on Income and Living Conditions*, EU-SILC). Celles-ci sont non seulement bien fournies en termes de renseignements collectés sur la composition du ménage (informations individuelles des membres du ménage avec sexe, âge, lieu de naissance, lieu de vie, situation matrimoniale, participation au budget du ménage et situation professionnelle) mais également sur les revenus (dépenses diverses, épargne, revenus du capital, prestations sociales, impôts) et les privations matérielles (caractérisation précise du logement et équipements). Elles sont néanmoins légèrement moins adaptées aux données subjectives que le Baromètre mais comportement toutefois un module « attitudes, sentiments et qualité de vie » (se sentir chanceux, optimisme sur l'avenir, inquiétude sur les revenus futurs, situer son revenu par rapport aux autres, satisfaction concernant son salaire et ses conditions de travail). 

En termes de méthodologie, un point qu’il serait important d’étudier est certainement la correction des données manquantes. Étant relativement peu nombreuses, le choix a été fait de se limiter uniquement à l’imputation des revenus par moyennes conditionnelles lorsque ceux-ci sont uniquement renseignés en tranche et d’écarter de la base de données les individus ne se prononçant pas sur au moins une question parmi celles mobilisées (indicateurs de pauvreté tout comme contrôles). Toutefois, il y a fort à parier que la non-réponse ne soit pas répartie équitablement dans tous les groupes sociaux et que l’échantillon utilisé biaise alors les résultats obtenus. 

Par ailleurs, même si les méthodes d’analyse factorielle sont très informatisées et souvent mobilisées via des logiciels « presse boutons », elles demandent en réalité une certaine expertise (technique d’analyse, nombre de facteurs à interpréter, type de rotation…). Les résultats et l’interprétation qui en découlent nécessitent une bonne taille d’échantillon et un choix judicieux des variables. Comme dans les modèles économétriques, les variables doivent être discriminantes (deux variables trop corrélées peuvent amener à des cas Heywood) mais elles doivent aussi ici être suffisamment corrélées pour constituer des facteurs. Les données devraient en toute rigueur être distribuées normalement et être liées linéairement entre elles pour pouvoir être estimées par maximum de vraisemblance. Certains points méthodologiques mériteraient donc certainement d’être approfondis par des regards d’experts pour affiner les conclusions tirées des différents modèles.  
