---
title: |
    | Résultats complémentaires 
subtitle : "pour l'article de recherche"
author: |
    | Kim Antunez
automaticcontents: true
output:
  bookdown::pdf_document2:
        toc: false
        toc_depth: 2
        number_sections: false
        fig_caption: true
        highlight: default
        keep_tex: no
        includes:
          in_header: preamble.tex
themeoptions: "coding=utf8,language=french"
classoption: 'french'
fontsize: 11pt
geometry: margin=0.90in
lang: "french"
documentclass: "article"
---

```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
#library(rmdformats)

## Global options
#options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=FALSE,
               prompt=FALSE,
               tidy=FALSE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.width = 5,
               fig.height = 3
               )
options(knitr.kable.NA = '')
#opts_knit$set(width=75)
```

```{r}
#chargement des packages
library(knitr)
library(dplyr) #manipuler les bases de données
library(tidyr) #pour pivot_longer
library(ggplot2) #pour les graphiques
library(RColorBrewer) #pour les palettes de couleur
```

```{r}
#chargement des packages
library(psych) #EFA
library(lavaan) #CFA et SEM
library(semPlot) #path draw CFA SEM
library(poLCA) #pour les Latent Categorical Variables
library(ade4) #pour la fonction s5 de plot des classes de CAH
library(tibble) #pour rownames_to_column
library(DiagrammeR) #pour refaire les graphiques de path
```

```{r, echo=FALSE}
#Chargement de la base de données
bdd <- readRDS("../data/2019/barometre2000_2019_diff.rds") %>% 
  filter(annee%in%2015:2019) #NEW : 2015 à 2019

revenus_a_imputer <- bdd %>%
  mutate(sdrevcl = ifelse(sdrevcl==999999999,NA,sdrevcl)) %>%
  group_by(sdrevtr) %>% 
  summarise(sdrevcl = mean(sdrevcl,na.rm=TRUE))


bdd <- bdd %>% 
  mutate(
    sdrevcl_imput_moy = case_when(
      sdrevcl!=999999999 ~ sdrevcl,
      sdrevcl==999999999 & sdrevtr==1 ~ revenus_a_imputer$sdrevcl[1],
      sdrevcl==999999999 & sdrevtr==2 ~ revenus_a_imputer$sdrevcl[2],
      sdrevcl==999999999 & sdrevtr==3 ~ revenus_a_imputer$sdrevcl[3],
      sdrevcl==999999999 & sdrevtr==4 ~ revenus_a_imputer$sdrevcl[4],
      sdrevcl==999999999 & sdrevtr==5 ~ revenus_a_imputer$sdrevcl[5],
      sdrevcl==999999999 & sdrevtr==6 ~ revenus_a_imputer$sdrevcl[6],
      sdrevcl==999999999 & sdrevtr==7 ~ revenus_a_imputer$sdrevcl[7]
             )
  )

bdd <- bdd %>% 
   mutate(seuil_pauvrete = do.call(c,lapply(annee,function(annee_selec){
0.6*median(bdd[bdd$annee==annee_selec,"sdrevcl_imput_moy"]/bdd[bdd$annee==annee_selec,"sduc"],
           na.rm=TRUE)
}
))) %>% 
  mutate(subj_inf_mini_decla = factor(
     sdrevcl_imput_moy - ifelse(pe16==999999999,NA,pe16) <0,
     levels=c(TRUE,FALSE),
     labels=paste0("-",c("Rev. inf. au minimum décla.","Rev. sup. au minimum décla.")))
     ) %>%
   # mutate(subj_inf_mini_decla = sdrevcl_imput_moy - ifelse(pe16==999999999,NA,pe16) <0) %>% 
  mutate(subj_pauvrete = 
           ifelse(pe3==3, TRUE,ifelse(pe3==4,NA,FALSE))) %>% 
  mutate(subj_risque_pauvrete = 
           ifelse(pe3==1, TRUE,ifelse(pe3==4,NA,FALSE))) %>% 
  mutate(subj_pauvrete_et_risque = 
           factor(
           ifelse(pe3==4, NA, ifelse(pe3==1,2,ifelse(pe3==2,1,3))),
           labels=c("Non pauvre","Risque pauvreté futur", "Déjà pauvre"))
         ) %>% 
  mutate(subj_besoin_aide_etat =
                   ifelse(pe15==2, TRUE,ifelse(pe15==4,NA,FALSE))) %>%
  mutate(obj_pauvrete= sdrevcl_imput_moy/sduc<seuil_pauvrete) %>% 
  #NEW KIM NOV
  mutate(insti_rsa = ifelse(sdres_3==1, TRUE,ifelse(sdres_3==3,NA,FALSE))) %>% 
  mutate(insti_cho = ifelse(sdres_4==1, TRUE,ifelse(sdres_4==3,NA,FALSE))) %>% 
  mutate(insti_apl = ifelse(sdres_9==1, TRUE,ifelse(sdres_9==3,NA,FALSE))) %>% 
  mutate(insti_cho_rsa = ifelse(sdres_3==1 | sdres_4==1, TRUE,ifelse(sdres_3==3 & sdres_4==3,NA,FALSE))) 
  
```

```{r, echo=FALSE}
bdd_logit <- bdd %>%
  mutate(nivie = sdrevcl_imput_moy/sduc) %>% 
  mutate(quantile_nivie = factor(
    cut(sdrevcl_imput_moy/sduc, include.lowest=TRUE,
        breaks=quantile(sdrevcl_imput_moy/sduc,
                        probs=seq(0,1,0.2),na.rm=TRUE),
        labels=1:5),
    levels=c(2,1,3,4,5),
    labels=paste0("-Quintile ",c(2,1,3,4,5)))
  ) %>% 
  mutate(
    statact = factor(case_when(
      sdsitua==1 & sdstatemp%in%c(1)   ~ 1,
      sdsitua%in%c(2,3) | (sdsitua==1 & sdstatemp%in%c(NA,2,3,4,5)) ~ 2,
      sdsitua==4 ~ 3,
      sdsitua==5 ~ 4,
      sdsitua==6 ~ 5,
      sdsitua==7 ~ 6,
      TRUE ~ NA_real_
    ),
    levels=1:6,
    labels=paste0("-",
                  c("CDI temps plein",
                    "Emploi précaire ou à temps partiel",
                    "Recherche d’emploi",
                    "Étudiant",
                    "Retraité",
                    "Aucune activité professionnelle"))
    )) %>% 
  mutate(prof = factor(
    #ifelse(sdpcs7!=7,sdpcs7,NA),
    sdpcs7,
    levels=c(4,1,2,3,5,6,7),
    labels=paste0("-",c("Profession intermédiaire","Agriculteur",
                        "Artisan commerçant","Cadre supérieur, profession libérale",
                        "Employé","Ouvrier","Aucune"))
  )) %>%
  # fastDummies::dummy_cols(select_columns = 'prof') %>% 
  mutate(
    diplome = factor(case_when(
      sddipl%in%c(1,2,3,4) ~ 1,
      sddipl%in%c(5,6) ~ 2,
      sddipl%in%c(7) ~ 3,
      sddipl%in%c(8) ~ 4,
      TRUE ~ NA_real_
    ),
    levels=c(2,1,3,4),
    labels=paste0("-",c("Baccalauréat","CAP, BEP ou moins","Bac + 2","Bac + 3 ou plus"))
    )) %>% 
  mutate(aide_log = factor(
    ifelse(sdres_9!=3,sdres_9,NA),
    levels=c(2,1),
    labels=paste0("-",c("Pas d'aide au logement","Aide au logement reçue"))
  )) %>% 
  mutate(aide_rsa = factor(
    ifelse(sdres_3!=3,sdres_3,NA),
    levels=c(2,1),
    labels=paste0("-",c("Pas de RSA","RSA reçu"))
  )) %>% 
  mutate(aide_handi = factor(
    ifelse(sdres_10!=3,sdres_10,NA),
    levels=c(2,1),
    labels=paste0("-",c("Pas d'alloc. hand./invalid./dépend.",
                        "Alloc. hand./invalid./dépend. reçu"))
  )) %>% 
  mutate(sexe = factor(
    ifelse(sdsexe!=3,sdsexe,NA),
    levels=c(2,1),
    labels=paste0("-",c("Femme","Homme"))
  )) %>% 
  mutate(age_tranche = factor(
    cut(sdage,
        breaks=c(18,30,40,50,60,70,120),
        include.lowest=TRUE,
        labels=1:6),
    levels=c(2,1,3,4,5,6),
    labels=paste0("-",c("30 à 39 ans","18 à 29 ans","40 à 49 ans",
                        "50 à 59 ans","60 à 69 ans", "70 ans et plus")))
  ) %>% 
  mutate(
    vie_fam = factor(case_when(
      sdsitfam==1 ~ 1,
      sdsitfam==2 & sdnbenf==1 ~ 2, #attention dépend des bases
      sdsitfam==2 & sdnbenf!=1 ~ 3, #attention dépend des bases
      sdsitfam==3 ~ 4,
      sdsitfam==4 ~ 5,
      sdsitfam%in%c(5,6,7) ~ 6,
      TRUE ~ NA_real_
    ),
    levels=c(2,1,3,4,5,6),
    labels=paste0("-",
                  c("Membre du couple (pas d’enfants à charge)","Vit seul",
                    "Membre du couple (enfants à charge)", "Chef famille monoparentale",
                    "Enfant","Autre"))
    )) %>% 
  mutate(
    statut_occup0 = factor(case_when(
      lo1%in%c(2,3,4)  ~ 1,
      lo1==1 ~ 2,
      lo1==5 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Locataire ou hébergé","Propriétaire")) 
    )) %>% 
  mutate(annee_fac = factor(annee,labels=paste0("-",2015:2019))) %>%  #NEW : 2015 à 2019
  mutate(pauvrete_mon_rel= factor(
    ifelse(sdrevcl_imput_moy/sduc<seuil_pauvrete,3,
                                  ifelse(sdrevcl_imput_moy/sduc>=1.2*seuil_pauvrete,1,
                                         ifelse(sdrevcl_imput_moy/sduc<1.2*seuil_pauvrete &
                                                  sdrevcl_imput_moy/sduc>=seuil_pauvrete ,
                                                2,NA)
                                  )),
    levels=c(1,2,3),
    labels=paste0("-",c("Revenus > 20 pourcents seuil pauvreté",
                        "Entre le seuil et 20 pourcents au dessus",
                        "Pauvreté monétaire"))
  )
  )

#NEW depuis fiche 3
bdd_logit <- bdd %>% 
   mutate(nivie = sdrevcl_imput_moy/sduc) %>% 
  mutate(quantile_nivie = factor(
    cut(sdrevcl_imput_moy/sduc, include.lowest=TRUE,
        breaks=quantile(sdrevcl_imput_moy/sduc,
                        probs=seq(0,1,0.2),na.rm=TRUE),
        labels=1:5),
    levels=c(2,1,3,4,5),
    labels=paste0("-Quintile ",c(2,1,3,4,5)))
  ) %>% 
  mutate(
    statact = factor(case_when(
      sdsitua==1 & sdstatemp%in%c(1)   ~ 1,
      sdsitua%in%c(2,3) | (sdsitua==1 & sdstatemp%in%c(NA,2,3,4,5)) ~ 2,
      sdsitua==4 ~ 3,
      sdsitua==5 ~ 4,
      sdsitua==6 ~ 5,
      sdsitua==7 ~ 6,
      TRUE ~ NA_real_
    ),
    levels=1:6,
    labels=paste0("-",
                  c("CDI temps plein",
                    "Emploi précaire ou à temps partiel",
                    "Recherche d’emploi",
                    "Étudiant",
                    "Retraité",
                    "Aucune activité professionnelle"))
    )) %>%
  # fastDummies::dummy_cols(select_columns = 'prof') %>% 
  mutate(
    diplome = factor(case_when(
      sddipl%in%c(1,2,3,4) ~ 1,
      sddipl%in%c(5,6) ~ 2,
      sddipl%in%c(7) ~ 3,
      sddipl%in%c(8) ~ 4,
      TRUE ~ NA_real_
    ),
    levels=c(2,1,3,4),
    labels=paste0("-",c("Baccalauréat","CAP, BEP ou moins","Bac + 2","Bac + 3 ou plus"))
    )) %>% 
  mutate(aide_log = factor(
    ifelse(sdres_9!=3,sdres_9,NA),
    levels=c(2,1),
    labels=paste0("-",c("Pas d'aide au logement","Aide au logement reçue"))
  )) %>% 
  mutate(aide_rsa = factor(
    ifelse(sdres_3!=3,sdres_3,NA),
    levels=c(2,1),
    labels=paste0("-",c("Pas de RSA","RSA reçu"))
  )) %>% 
  mutate(aide_handi = factor(
    ifelse(sdres_10!=3,sdres_10,NA),
    levels=c(2,1),
    labels=paste0("-",c("Pas d'alloc. hand./invalid./dépend.",
                        "Alloc. hand./invalid./dépend. reçu"))
  )) %>% 
  mutate(sexe = factor(
    ifelse(sdsexe!=3,sdsexe,NA),
    levels=c(2,1),
    labels=paste0("-",c("Femme","Homme"))
  )) %>% 
  mutate(age_tranche = factor(
    cut(sdage,
        breaks=c(18,30,40,50,60,70,120),
        include.lowest=TRUE,
        labels=1:6),
    levels=c(2,1,3,4,5,6),
    labels=paste0("-",c("30 à 39 ans","18 à 29 ans","40 à 49 ans",
                        "50 à 59 ans","60 à 69 ans", "70 ans et plus")))
  ) %>% 
  mutate(
    vie_fam = factor(case_when(
      sdsitfam==1 ~ 1,
      #sdsitfam==2 & sdnbenf==0 ~ 2,
      #sdsitfam==2 & sdnbenf!=0 ~ 3,
      sdsitfam==2 & sdnbenf==1 ~ 2,
      sdsitfam==2 & sdnbenf!=1 ~ 3,
      sdsitfam==3 ~ 4,
      sdsitfam==4 ~ 5,
      sdsitfam%in%c(5,6,7) ~ 6,
      TRUE ~ NA_real_
    ),
    levels=c(2,1,3,4,5,6),
    labels=paste0("-",
                  c("Membre du couple (pas d’enfants à charge)","Vit seul",
                    "Membre du couple (enfants à charge)", "Chef famille monoparentale",
                    "Enfant","Autre situation familiale"))
    )) %>% 
  mutate(
    statut_occup0 = factor(case_when(
      lo1%in%c(2,3,4)  ~ 1,
      lo1==1 ~ 2,
      lo1==5 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Locataire ou hébergé","Propriétaire ")) 
    )) %>% 
  mutate(
    statut_occup = factor(case_when(
      lo1%in%c(3,4)  ~ 1,
      lo1==2  ~ 2,
      lo1==1 ~ 3,
      lo1==5 ~ NA_real_
   ),
    levels=c(1,2,3),
    labels=paste0("-",
                  c("Locataire privé / hébergé",
                    "Locataire HLM","Propriétaire")) 
    )) %>% 
  mutate(annee_fac = factor(annee,labels=paste0("-",2015:2019))) %>% 
  mutate(annee_fac_paires = factor(ifelse(annee%in%c(2016,2018),annee,NA),labels=paste0("-",c(2016,2018)))) %>% 
  mutate(pauvrete_mon_rel= factor(
    ifelse(sdrevcl_imput_moy/sduc<seuil_pauvrete,3,
                                  ifelse(sdrevcl_imput_moy/sduc>=1.2*seuil_pauvrete,1,
                                         ifelse(sdrevcl_imput_moy/sduc<1.2*seuil_pauvrete &
                                                  sdrevcl_imput_moy/sduc>=seuil_pauvrete ,
                                                2,NA)
                                  )),
    levels=c(1,2,3),
    labels=paste0("-",c("Revenus > 20 pourcents seuil pauvreté",
                        "Entre le seuil et 20 pourcents au dessus",
                        "Pauvreté monétaire"))
  )
  )

# bdd_logit <- bdd_logit %>% mutate(sdniviecl_imput_quint = 
# factor(
#     cut(sdniviecl_imput, include.lowest=TRUE,
#         breaks=quantile(sdniviecl_imput,
#                         probs=seq(0,1,0.2),na.rm=TRUE),
#         labels=1:5),
#     levels=c(2,1,3,4,5),
#     labels=paste0("-Quintile ",c(2,1,3,4,5))))

#NEW depuis fiche 3
bdd_logit <- bdd_logit %>% #chômeur indemnise 
  mutate(
    conn_choindemnise = factor(case_when(
      sdproxim_1%in%c(1,4)  ~ 1,
      sdproxim_1%in%c(2,3,5,6,7,8)  ~ 2,
      sdproxim_1==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Ne connaît pas de chômeur indemnisé",
                    "Connait un chômeur indemnisé")) 
    )) %>% 
  mutate(
    est_choindemnise = factor(case_when(
      sdproxim_1%in%c(4,6,7,8)  ~ 2,
      sdproxim_1%in%c(1,2,3,5)  ~ 1,
      sdproxim_1==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("N'est pas chômeur indemnisé",
                    "est chômeur indemnisé")) 
    )) %>%
  mutate(
    conn_chononindemnise = factor(case_when(
      sdproxim_2%in%c(1,4)  ~ 1,
      sdproxim_2%in%c(2,3,5,6,7,8)  ~ 2,
      sdproxim_2==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Ne connaît pas de chômeur non indemnisé",
                    "Connait un chômeur non indemnisé")) 
    )) %>% 
  mutate(
    est_chononindemnise = factor(case_when(
      sdproxim_2%in%c(4,6,7,8)  ~ 2,
      sdproxim_2%in%c(1,2,3,5)  ~ 1,
      sdproxim_2==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("N'est pas chômeur non indemnisé",
                    "est chômeur non indemnisé")) 
    )) %>% #SDF
  mutate(
    conn_sdf = factor(case_when(
      sdproxim_3%in%c(1,4)  ~ 1,
      sdproxim_3%in%c(2,3,5,6,7,8)  ~ 2,
      sdproxim_3==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Ne connaît pas de SDF",
                    "Connait un SDF")) 
    )) %>% 
  mutate(
    est_sdf = factor(case_when(
      sdproxim_3%in%c(4,6,7,8)  ~ 2,
      sdproxim_3%in%c(1,2,3,5)  ~ 1,
      sdproxim_3==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("N'est pas SDF",
                    "est SDF")) 
    )) %>% #personne élevant seul ses enfants avec moins du SMIC 
  mutate(
    conn_eleveseulsmic = factor(case_when(
      sdproxim_4%in%c(1,4)  ~ 1,
      sdproxim_4%in%c(2,3,5,6,7,8)  ~ 2,
      sdproxim_4==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Ne connaît pas de personne élevant seul ses enfants avec moins du SMIC",
                    "Connait une personne élevant seul ses enfants avec moins du SMIC")) 
    )) %>% 
  mutate(
    est_eleveseulsmic = factor(case_when(
      sdproxim_4%in%c(4,6,7,8)  ~ 2,
      sdproxim_4%in%c(1,2,3,5)  ~ 1,
      sdproxim_4==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("N'est pas personne élevant seul ses enfants avec moins du SMIC",
                    "est personne élevant seul ses enfants avec moins du SMIC")) 
    )) %>% #pensionné invalide indicapé ne pouvant pas travailler 
  mutate(
    conn_pensionhandi = factor(case_when(
      sdproxim_5%in%c(1,4)  ~ 1,
      sdproxim_5%in%c(2,3,5,6,7,8)  ~ 2,
      sdproxim_5==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Ne connaît pas de pensionné invalide indicapé ne pouvant pas travailler",
                    "Connait un pensionné invalide indicapé ne pouvant pas travailler")) 
    )) %>% 
  mutate(
    est_pensionhandi = factor(case_when(
      sdproxim_5%in%c(4,6,7,8)  ~ 2,
      sdproxim_5%in%c(1,2,3,5)  ~ 1,
      sdproxim_5==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("N'est pas pensionné invalide indicapé ne pouvant pas travailler",
                    "est pensionné invalide indicapé ne pouvant pas travailler")) 
    )) %>% #personne en emploi précaire 
  mutate(
    conn_emploiprecaire = factor(case_when(
      sdproxim_6%in%c(1,4)  ~ 1,
      sdproxim_6%in%c(2,3,5,6,7,8)  ~ 2,
      sdproxim_6==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Ne connaît pas de personne en emploi précaire",
                    "Connait une personne en emploi précaire")) 
    )) %>% 
  mutate(
    est_emploiprecaire = factor(case_when(
      sdproxim_6%in%c(4,6,7,8)  ~ 2,
      sdproxim_6%in%c(1,2,3,5)  ~ 1,
      sdproxim_6==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("N'est pas personne en emploi précaire",
                    "est personne en emploi précaire")) 
    )) %>%  mutate(
    conn_rsa_fam = factor(case_when(
      sdproxim_7%in%c(1,3,4,7)  ~ 1,
      sdproxim_7%in%c(2,5,6,8)  ~ 2,
      sdproxim_7==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Ne connaît pas de personne dans sa famille au RSA",
                    "Connait une personne dans sa famille au RSA")) 
    )) %>%
   mutate(
    conn_rsa_horsfam = factor(case_when(
      sdproxim_7%in%c(1,2,4,6)  ~ 1,
      sdproxim_7%in%c(3,5,7,8)  ~ 2,
      sdproxim_7==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Ne connaît pas de personne hors de sa famille au RSA",
                    "Connait une personne hors de sa famille au RSA")) 
    )) %>% #personne au RSA 
  mutate(
    conn_rsa = factor(case_when(
      sdproxim_7%in%c(1,4)  ~ 1,
      sdproxim_7%in%c(2,3,5,6,7,8)  ~ 2,
      sdproxim_7==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Ne connaît pas de personne au RSA",
                    "Connait une personne au RSA")) 
    )) %>% 
  mutate(
    est_rsa = factor(case_when(
      sdproxim_7%in%c(4,6,7,8)  ~ 2,
      sdproxim_7%in%c(1,2,3,5)  ~ 1,
      sdproxim_7==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("N'est pas personne au RSA",
                    "est personne au RSA")) 
    )) %>% #personne handicapée de moins de 60 ans
  mutate(
    conn_handijeune = factor(case_when(
      sdproxim_8%in%c(1,4)  ~ 1,
      sdproxim_8%in%c(2,3,5,6,7,8)  ~ 2,
      sdproxim_8==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Ne connaît pas de personne handicapée de moins de 60 ans",
                    "Connait une personne handicapée de moins de 60 ans")) 
    )) %>% 
  mutate(
    est_handijeune = factor(case_when(
      sdproxim_8%in%c(4,6,7,8)  ~ 2,
      sdproxim_8%in%c(1,2,3,5)  ~ 1,
      sdproxim_8==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("N'est pas personne handicapée de moins de 60 ans",
                    "est personne handicapée de moins de 60 ans")) 
    )) %>% #personne âgée dépendante
  mutate(
    conn_dependant = factor(case_when(
      sdproxim_9%in%c(1,4)  ~ 1,
      sdproxim_9%in%c(2,3,5,6,7,8)  ~ 2,
      sdproxim_9==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Ne connaît pas de personne âgée dépendante",
                    "Connait une personne âgée dépendante")) 
    )) %>% 
  mutate(
    est_dependant = factor(case_when(
      sdproxim_9%in%c(4,6,7,8)  ~ 2,
      sdproxim_9%in%c(1,2,3,5)  ~ 1,
      sdproxim_9==9 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("N'est pas personne âgée dépendante",
                    "est personne âgée dépendante")) 
    )) %>% 
  mutate(
    revenus_salaires = factor(case_when(
      sdres_1%in%c(2)  ~ 1,
      sdres_1%in%c(1)  ~ 2,
      sdres_1==3 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Pas de revenus de salaires",
                    "Revenus de salaires")) 
    )) %>% 
  mutate(
    revenus_independant = factor(case_when(
      sdres_2%in%c(2)  ~ 1,
      sdres_2%in%c(1)  ~ 2,
      sdres_2==3 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Pas de revenus d'activité indépendante",
                    "Revenus d'activité indépendante")) 
    )) %>%
  mutate(
    presta_hlm = factor(case_when(
      lo1%in%c(1,3,4) ~ 1,
      lo1==2  ~ 2,
      lo1==5 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Locataire privé / hébergé, Propriétaire","Locataire HLM")) 
    )) %>% 
  mutate(
    presta_rsa = factor(case_when(
      sdres_3%in%c(2)  ~ 1,
      sdres_3%in%c(1)  ~ 2,
      sdres_3==3 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Pas de RSA",
                    "RSA")) 
    )) %>% 
  mutate(
    presta_chomage = factor(case_when(
      sdres_4%in%c(2)  ~ 1,
      sdres_4%in%c(1)  ~ 2,
      sdres_4==3 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Pas d'allocation chômage",
                    "Allocation chômage")) 
    )) %>% 
  mutate(
    revenus_retraite = factor(case_when(
      sdres_5%in%c(2)  ~ 1,
      sdres_5%in%c(1)  ~ 2,
      sdres_5==3 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Pas de revenus de retraite",
                    "Revenus de retraite")) 
    )) %>%
  mutate(
    revenus_financiers = factor(case_when(
      sdres_6%in%c(2)  ~ 1,
      sdres_6%in%c(1)  ~ 2,
      sdres_6==3 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Pas de revenus d'actifs financiers",
                    "Revenus d'actifs financiers")) 
    )) %>% 
  mutate(
    revenus_locatifs = factor(case_when(
      sdres_7%in%c(2)  ~ 1,
      sdres_7%in%c(1)  ~ 2,
      sdres_7==3 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Pas de revenus de locations",
                    "Revenus de locations")) 
    )) %>% 
  mutate(
    presta_fam = factor(case_when(
      sdres_8%in%c(2)  ~ 1,
      sdres_8%in%c(1)  ~ 2,
      sdres_8==3 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Pas de prestations familiales",
                    "Prestations familiales")) 
    )) %>% 
  mutate(
    presta_apl = factor(case_when(
      sdres_9%in%c(2)  ~ 1,
      sdres_9%in%c(1)  ~ 2,
      sdres_9==3 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Pas d'APL",
                    "APL")) 
    )) %>% 
  mutate(
    presta_handi = factor(case_when(
      sdres_10%in%c(2)  ~ 1,
      sdres_10%in%c(1)  ~ 2,
      sdres_10==3 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Pas d'AAH, APA, PCH (handicap)",
                    "AAH, APA, PCH (handicap)")) 
    )) %>% 
  mutate(
    presta_etudes = factor(case_when(
      sdres_11%in%c(2)  ~ 1,
      sdres_11%in%c(1)  ~ 2,
      sdres_11==3 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Pas de bourse d'étude",
                    "Bourse d'étude")) 
    )) %>% 
  mutate(
    presta_pensionalim = factor(case_when(
      sdres_12%in%c(2)  ~ 1,
      sdres_12%in%c(1)  ~ 2,
      sdres_12==3 ~ NA_real_
   ),
    levels=c(1,2),
    labels=paste0("-",
                  c("Pas de pension alimentaire",
                    "pension alimentaire")) 
    )) %>% 
  mutate(
    statut_activite = factor(case_when(
      sdstat==2 & (sdsitua==1 & sdstatemp==1) ~ 1,
      sdstat==2 & !(sdsitua==1 & sdstatemp==1) ~ 2,
      sdstat==1 & (sdsitua==1 & sdstatemp==1) ~ 3,
      sdstat==1 & !(sdsitua==1 & sdstatemp==1) ~ 4,
      sdstat==3 ~ 5,
      sdstat==4 ~ 6,
      sdstat==5 ~ 7,
      sdstat==6 ~ 8,
      sdstat==7 ~ 9,
      sdstat==8 ~ NA_real_
   ),
    levels=1:9,
    labels=paste0("-",
                  c("Salarié du secteur privé (en CDI à temps plein)",
"Salarié du secteur privé (précaire ou à temps partiel)",
"Salarié du secteur public (en CDI à temps plein)",
"Salarié du secteur public (précaire ou à temps partiel)",
"Indépendant sans salarié",
"Employeur",
"Chômeur",
"Inactif",
"Autre statut d'activité")
) 
    )) %>% 
  mutate(prof = factor(
    sdpcs7,
    levels=c(4,1,2,3,5,6,7),
    labels=paste0("-",c("Profession intermédiaire","Agriculteur",
                        "Artisan commerçant","Cadre supérieur, profession libérale",
                        "Employé","Ouvrier","Aucune"))
  ))  %>% 
  mutate(prof_statut_act = factor(
    sdpcs10,
    levels=c(4,1,2,3,5,6,7,8,9,10),
    labels=paste0("-",c("Profession intermédiaire","Agriculteur",
                        "Artisan commerçant","Cadre supérieur, profession libérale",
                        "Employé","Ouvrier","Chômeur",
                        "Retraité","Au foyer","Autre inactif"))
  )) %>%
  mutate(
    statut_activite_resp = factor(case_when(
      sdprstat==2 & (sdprsitua==1) ~ 1,
      sdprstat==2 & !(sdprsitua==1) ~ 2,
      sdprstat==1 & (sdprsitua==1) ~ 3,
      sdprstat==1 & !(sdprsitua==1) ~ 4,
      sdprstat==3 ~ 5,
      sdprstat==4 ~ 6,
      sdprstat==5 ~ 7,
      sdprstat==6 ~ 8,
      sdprstat==7 ~ 9,
      sdprstat==8 ~ NA_real_
   ),
    levels=1:9,
    labels=paste0("-Pers. réf. ",
                  c("Salarié du secteur privé (à temps plein)",
"Salarié du secteur privé (à temps partiel)",
"Salarié du secteur public (à temps plein)",
"Salarié du secteur public (à temps partiel)",
"Indépendant sans salarié",
"Employeur",
"Chômeur",
"Inactif",
"Autre statut d'activité")
) 
    )) %>% 
  mutate(prof_resp = factor(
    sdprpcs7,
    levels=c(4,1,2,3,5,6,7),
    labels=paste0("-Pers. réf. ",c("Profession intermédiaire","Agriculteur",
                        "Artisan commerçant","Cadre supérieur, profession libérale",
                        "Employé","Ouvrier","Aucune"))
  )) %>% 
  mutate(prof_statut_act_resp = factor(
    sdprpcs10,
    levels=c(4,1,2,3,5,6,7,8,9,10),
    labels=paste0("-Pers. réf. ",c("Profession intermédiaire","Agriculteur",
                        "Artisan commerçant","Cadre supérieur, profession libérale",
                        "Employé","Ouvrier","Chômeur",
                        "Retraité","Au foyer","Autre inactif"))
  ))


```


# Tableau A.1

```{r, echo=FALSE, fig.width = 4}
variables <- c("revenus_locatifs", "revenus_financiers", "quantile_nivie", "presta_rsa","presta_chomage","presta_fam", "presta_apl","presta_handi", "presta_etudes", "subj_pauvrete", "subj_inf_mini_decla", "sexe", "age_tranche", "prof_statut_act", "vie_fam", "statut_occup", "diplome")
variables_lib <- c("Revenus de locations", "Revenus d'actifs financiers", "Niveau de vie", "RSA (Revenu de solidarité active)", "Allocation de chômage", "Prestations familiales (allocations familiales, complément familial, prestation d’accueil du jeune enfant, …)", "Allocation de logement (APL, …)", "Prestations liées au handicap, à l’invalidité ou à la dépendance (AAH, APA, PCH, …)", "Bourses d’études", "Sentiment de pauvreté", "Difficultés financières perçues", "Sexe", "Tranche d’âge", "Situation sur le marché du travail", "Situation familiale", "Statut d’occupation du logement", "Niveau du diplôme")

df_fin <- NULL
for(i in 1:length(variables)){
df <- as.data.frame(round(100*table(bdd_logit[,variables[i]])/sum(
  table(bdd_logit[,variables[i]])))) 
df$Var1 <- gsub("-","",df$Var1)
df <- rbind(data.frame(Var1=variables_lib[i], Freq=NA),df)
df_fin <- rbind(df_fin, df)  
}
colnames(df_fin) <- c("Variables et modalités", "% sur les années 2015 à 2019")
df_fin[c(2,5,14,17,20,23,26, 29, 32, 36),1]<- "Non"
df_fin[c(3,6,15,18,21,24,27, 30, 33, 35),1]<- "Oui"
for(couple in list(c(8,9),c(41,42),c(48,49),c(49,50),c(59,60),c(70,71))){
  df_fin[couple,] <- df_fin[rev(couple),]
}

tableauA1 <- df_fin %>% 
            kable(format = 'latex', booktabs = TRUE,
                  longtable = TRUE 
                  ) %>%  
            kableExtra::column_spec(1, width = "8cm") %>% 
            kableExtra::column_spec(2, width = "4cm") %>% 
            kableExtra::row_spec(c(1,4,7,13,16,19,22,25,28,31,34,37,40,47,58,65,69),bold=TRUE)

tableauA1
```

# Figure 1

```{r, fig.height=3, fig.width=6}
fig_intro <- bdd_logit %>%
  filter(annee==2019 & !is.na(quantile_nivie)) %>% 
  mutate(quantile_nivie = factor(quantile_nivie,
         levels=paste0("-Quintile ",c(1,2,3,4,5)),
         labels=paste0("Quintile ",c(1,2,3,4,5))
           )) %>% 
  group_by(quantile_nivie) %>% 
  count(pe3, wt=poids) %>% 
  mutate(n = 100*n/sum(n)) %>% 
  ungroup() %>% 
  mutate(#quantile_nivie=factor(quantile_nivie,labels=names(attr(bdd$quantile_nivie,"labels"))),
         pe3=factor(pe3,labels=
           c(names(attr(bdd$pe3,"labels"))[1:2],"Je me considère déjà\ncomme pauvre",names(attr(bdd$pe3,"labels"))[4])), 
         pe3=factor(pe3,levels=levels(pe3)[c(4,2,1,3)])) %>% 
  ggplot(aes(x=quantile_nivie, y=n, fill=pe3)) +
  geom_bar(stat="identity") + coord_flip() +
  labs(
   # title="Sentiment de pauvreté en fonction du niveau de vie en 2019",
    y="Part (%)", x="Niveau de vie") +
  theme_minimal() +
  scale_fill_manual(name= paste(strwrap(gsub("PE3. ","",attr(bdd$pe3,"label")),30),collapse="\n"),
                    #values=rev(c('red','orange','lightgreen','gray')),
                    values=brewer.pal(6,"Greys")[2:5], 
                    guide=guide_legend(reverse=TRUE)) + 
  geom_text(aes(label = paste0(round(n,0))), 
            position = position_stack(vjust = 0.5))

fig_intro
```

```{r, echo=FALSE, fig.width = 4, eval=FALSE}
data_fig1 <- bdd %>%
  filter(annee == 2019)  %>%
  summarise(subj_pauvrete = round(100*weighted.mean(subj_pauvrete,poids, na.rm=TRUE)),
            obj_pauvrete = round(100*weighted.mean(obj_pauvrete, poids, na.rm=TRUE)),
            insti_cho_rsa = round(100*weighted.mean(insti_cho_rsa ,poids, na.rm=TRUE))
              ) 

fig1 <- ggplot(
  data=data.frame(data_fig1) %>% tidyr::pivot_longer(cols=colnames(.)),
  aes(x=name, y=value, fill=name)) +
  geom_bar(stat="identity", position=position_dodge())+
  geom_text(aes(label=value), vjust=1.6, color="white", position = position_dodge(0.9), size=3.5)+
  scale_fill_manual(values = brewer.pal(4,"Greys")[2:4])+
  theme_minimal() +
  scale_x_discrete(name ="Part des Français concernés (%)",
                   limits=c("subj_pauvrete",
                            "obj_pauvrete",
                            "insti_cho_rsa"),
                   labels=c(
      "subj_pauvrete" = "Sentiment\nde pauvreté",
      "obj_pauvrete" = "Pauvreté\nmonétaire\nobjective",
      #"subj_besoin_aide_etat"="Besoin de\nplus d'aide\npublique",
      "insti_cho_rsa" = "Part des bénéfi-\nciaires du RSA\nou du chômage"
      ))+
  ylab("") +
  theme(legend.position="none")
fig1
#saveRDS(fig_chap1_compa20152019,"../rapport/figures/fig_chap1_compa20152019.RDS")
#saveRDS(fig_chap1_compa20152019,"../rapport/figures/fig_chap1_compa20152019.RDS")
```


# Figure 2

```{r, echo=FALSE, fig.width = 8, fig.height=3.5}
data_g1_new_effectifs <- bdd %>%
  mutate(subj_inf_mini_decla=ifelse(subj_inf_mini_decla=="-Rev. inf. au minimum décla.",TRUE,FALSE)) %>% 
   group_by(annee) %>% 
   summarise(subj_pauvrete = sum(!is.na(subj_pauvrete)),
             subj_inf_mini_decla = sum(!is.na(subj_inf_mini_decla)),
             obj_pauvrete = sum(!is.na(obj_pauvrete)),
             subj_besoin_aide_etat = sum(!is.na(subj_besoin_aide_etat)),
             insti_rsa = sum(!is.na(insti_rsa)),
             insti_apl = sum(!is.na(insti_apl)),
             insti_cho = sum(!is.na(insti_cho)) 
             )


data_g1_new <- bdd %>%
  mutate(subj_inf_mini_decla=ifelse(subj_inf_mini_decla=="-Rev. inf. au minimum décla.",TRUE,FALSE)) %>% 
  group_by(annee) %>%
    summarise(subj_pauvrete = round(100*weighted.mean(subj_pauvrete,
                                                             poids, na.rm=TRUE)),
                            subj_inf_mini_decla = round(100*weighted.mean(subj_inf_mini_decla, poids, na.rm=TRUE)),
            obj_pauvrete = round(100*weighted.mean(obj_pauvrete,
                                                             poids, na.rm=TRUE)),
              
              subj_besoin_aide_etat = round(100*weighted.mean(subj_besoin_aide_etat,
                                                         poids, na.rm=TRUE)),
            
            insti_rsa = round(100*weighted.mean(insti_rsa ,
                                                         poids, na.rm=TRUE)),
            insti_apl = round(100*weighted.mean(insti_apl ,
                                                         poids, na.rm=TRUE)),
            insti_cho = round(100*weighted.mean(insti_cho ,
                                                         poids, na.rm=TRUE)),
            
            
              ) 

data_g1_new_ic <- cbind(data_g1_new[,1],
                        1.96*100*sqrt(apply(data_g1_new,2,as.numeric)/100 * (1-apply(data_g1_new,2,as.numeric)/100)/apply(data_g1_new_effectifs,2,as.numeric))[,-1])




fig_chap1_compa20152019_new <- ggplot(
  data=cbind(data_g1_new %>% tidyr::pivot_longer(!annee),
             data_g1_new_ic %>% tidyr::pivot_longer(!annee) %>% dplyr::select(value) 
  ) %>% setNames(c("annee","name","value","ic")),
       aes(x=name, y=value, fill=annee)) +
  geom_bar(stat="identity", position=position_dodge())+
  geom_errorbar(aes(ymin = value - ic, ymax = value + ic), width = 0.2, position = position_dodge(0.9)) +
  geom_text(aes(label=value), vjust=1.6, color="white",
            position = position_dodge(0.9), size=3.5)+
  scale_fill_manual(
    #values = c(rev(brewer.pal(5,"Purples")[3:5]),brewer.pal(4,"Oranges")[3:4])
    values = brewer.pal(6,"Greys")[2:6]
                    )+
  theme_minimal() +
  scale_x_discrete(name ="Part des Français concernés (%)",
                   limits=c("subj_pauvrete",
                            "subj_inf_mini_decla",
                            "obj_pauvrete",
                            #"subj_besoin_aide_etat",
                            "insti_rsa",
                            "insti_apl",
                            "insti_cho"),
                   labels=c(
      "subj_pauvrete" = "Sentiment\nde pauvreté",
      "subj_inf_mini_decla" = "Difficultés financières\nperçues",
      "obj_pauvrete" = "Pauvreté\nmonétaire\nobjective",
      #"subj_besoin_aide_etat"="Besoin de\nplus d'aide\npublique",
      "insti_rsa" = "Part des bénéfi-\nciaires du RSA",
      "insti_apl" = "Part des bénéfi-\nciaires des APL",
      "insti_cho" = "Part des bénéfi-\nciaires du chômage"
      ))+
  #ggtitle("Graphique 1 : Différents indicateurs de pauvreté") +
  ylab("")+
  labs(fill="Année")
fig_chap1_compa20152019_new
#saveRDS(fig_chap1_compa20152019,"../rapport/figures/fig_chap1_compa20152019.RDS")
```

\newpage

# Tableau 1

```{r, echo=FALSE}
run_regression <- function(x,y="subj_pauvrete",type_mod="logit", bdd_log=bdd_logit, kable=TRUE){

f <- as.formula(paste(y, paste0(x,collapse = " + "), sep="~"))

if(type_mod=="logit"){
  repetitions <- 1
  reg <- do.call("glm", list(formula=f,
                             data = bdd_log %>% dplyr::select(c(all_of(y),all_of(x))) %>% tidyr::drop_na(),
                             family=binomial(logit)))
 coeffs <- summary(reg)$coefficients[,1]
 p <- summary(reg)$coefficients[,4]
} else if (type_mod=="multinomial"){
repetitions <- length(levels(bdd_log[,y])[-1])
reg <- do.call("multinom", list(formula=f,
                             data = bdd_log %>% dplyr::select(c(all_of(y),all_of(x))) %>% tidyr::drop_na(), trace = FALSE))
  coeffs <- as.vector(t(summary(reg)$coefficients))
  z <- summary(reg)$coefficients/summary(reg)$standard.errors
  p <- as.vector((1 - pnorm(abs(t(z)), 0, 1)) * 2)
} else if (type_mod=="ordinal"){ #NEW
repetitions <- 1
reg <- do.call("polr", list(formula=f,
                             data = bdd_log %>% dplyr::select(c(all_of(y),all_of(x))) %>% tidyr::drop_na()))
  coeffs <- summary(reg)$coefficients[,1]
  p <- as.vector((1 - pnorm(abs(summary(reg)$coefficients[,3]), 0, 1)) * 2)
}


  if(type_mod!="ordinal"){
   modalites <- c("(Intercept)")
   noms <- c("-(Intercept)")
  } else{
   modalites <- NULL
   noms <- NULL
  }
   for(var in x){
     if(is.factor(bdd_log[,var])){
       modalites <- c(modalites,gsub("-","",levels(bdd_log[,var])))
       noms <- c(noms, paste0(var,levels(bdd_log[,var])[-1]))
     }else{
       modalites <- c(modalites,var)
       noms <- c(noms,paste0("-",var))
     }
   }
if(type_mod=="ordinal"){
   modalites <- c(modalites,names(coeffs)[grep("\\|",names(coeffs))])
   noms <- c(noms,paste0("(Intercept)-",names(coeffs)[grep("\\|",names(coeffs))]))
   
  }   
  
   
  df_model  <- data.frame(noms= noms,
                          valeur=round(coeffs,2),
                          pvaleur=cut(p, breaks = c(0, 0.001, 0.01, 0.05, 1),
                                      include.lowest = TRUE,
                                      labels = c('***', '**', '*', '')),
                          row.names=NULL
   ) %>% mutate(noms = gsub("`","",noms)) %>%  
     tidyr::separate(noms,c("variable","modalite"),sep="-") %>% 
   #  mutate(odds=ifelse(is.na(pvaleur) | pvaleur=='',NA,round(exp(coeffs),2))) %>%  
      mutate(odds=round(exp(coeffs),2)) %>% 
     mutate(modalite_y =
              if(type_mod!="multinomial"){NA}else{rep(levels(bdd_log[,y])[-1],each=n()/repetitions)}) %>% 
     right_join(
       data.frame(
         modalite_y=if(type_mod!="multinomial"){NA}else{rep(levels(bdd_log[,y])[-1],each=length(modalites))},
         modalite=rep(modalites,repetitions)
         )
       ,by=c("modalite_y","modalite")
       ) %>% 
     arrange(match(modalite_y,levels(bdd_log[,y])[-1]),match(modalite, modalites))
   
   if(type_mod == "logit"){
    R2_ajuste <- with(summary(reg), 1 - deviance/null.deviance)
    N <- length(summary(reg)$deviance.resid)
   } else {
     if(type_mod=="multinomial"){
        ref <- do.call("multinom",
                   list(formula=paste0(y," ~ ", 1),
                             data = bdd_log %>% dplyr::select(c(all_of(y),all_of(x))) %>% tidyr::drop_na(), trace = FALSE))
  
     } else if (type_mod=="ordinal"){
        ref <- do.call("polr",
                   list(formula=paste0(y," ~ ", 1),
                             data = bdd_log %>% dplyr::select(c(all_of(y),all_of(x))) %>% tidyr::drop_na()))
       
     }
     R2_ajuste <- nnet.mod.mfr2 <- as.numeric(1 -
                                  nnet:::logLik.multinom(reg) /
                                  nnet:::logLik.multinom(ref)
    )
    N <- length(summary(reg)$fitted.values[,1])
   } 
   
  if(y=="subj_pauvrete"){
    titre_y <- "Se déclarer pauvre"
  } else if(y=="subj_inf_mini_decla"){
    titre_y <- "Revenu inférieur au minimum déclaré"
  } else if(y=="subj_risque_pauvrete"){
    titre_y <- "Penser avoir un risque de devenir pauvre dans 5 ans"
  } else if(y=="subj_besoin_aide_etat"){
    titre_y <- "Considérer ne pas être suffisamment aidé par les pouvoirs publics"
  } else if(y=="subj_pauvrete_et_risque"){
    titre_y <- "Réponse à la question sur le risque de devenir pauvre ou non dans 5 ans (Non, Oui, Non je le suis déjà)"
  } else if(y=="latent_classes"){
    titre_y <- "Classes latentes du modèle"
  } else{
    titre_y <- "Non répondants selon la variable indiquée en y"
  }
    
  tableau <- df_model %>% dplyr::select(modalite_y,modalite,valeur,pvaleur,odds)
    
if(kable){
  tableau <- tableau %>% setNames(c("","Modalités","Coefficients","p-valeurs","Odds")) %>% 
            kable(format = 'latex', booktabs = TRUE, longtable = TRUE) %>%  
            kableExtra::column_spec(1, width = ifelse(type_mod=="multinomial","4cm","0cm")) %>% 
            kableExtra::column_spec(2, width = "4cm") %>% 
            kableExtra::column_spec(3:5, width = "2cm") %>% 
            kableExtra::kable_styling(latex_options = c("hold_position", "repeat_header")) %>% 
            kableExtra::footnote(c(paste0("Modèle logit (Variable dépendante = ",titre_y,")")), paste0("N = ",
                                        N," / R2 ajusté = ",
                                        round(100*R2_ajuste,1)," %")) 
}
    
  return(tableau)
}
```



```{r, echo=FALSE}
#N = 13567 / R2 ajusté = 25.9
tab_final21_sentpauv <- run_regression(y="subj_pauvrete", 
               x= c("quantile_nivie","revenus_locatifs","revenus_financiers","presta_rsa","presta_apl","presta_chomage","presta_handi",
                    "presta_etudes",
                    "statut_occup", "prof_statut_act","est_emploiprecaire", "diplome", "age_tranche","vie_fam", "sexe", #"conn_rsa", 
                    "annee_fac"
), kable = FALSE) %>% 
  mutate(odds_ratio = ifelse(
    !is.na(valeur),paste0(gsub("\\.",",",odds),pvaleur),"Réf."
  )) %>% 
  dplyr::select(modalite_y,modalite,odds_ratio) %>% 
  slice(-1) %>% 
  # arrange(match(modalite, c(modalite[2],modalite[-2]))) %>% 
  # arrange(match(modalite, c(modalite[1:17],modalite[19],modalite[18],modalite[20:57]))) %>% 
  # arrange(match(modalite, c(modalite[1:20],modalite[22:24],modalite[21],modalite[25:57])))  %>% 
  # arrange(match(modalite, c(modalite[1:32],modalite[34],modalite[33],modalite[35:57]))) %>% 
  # arrange(match(modalite, c(modalite[1:36],modalite[38],modalite[37],modalite[39:57]))) %>% 
  # arrange(match(modalite, c(modalite[1:42],modalite[44],modalite[43],modalite[45:57]))) %>% 
  mutate(modalite_y = c("Niveau de vie",rep("",4),"Types de ressources ","perçues par le ménage ","(12 mois)",rep("",11),"Logement",rep("",2), "Situation professionnelle",rep("",9),"Précarité de l'emploi","(subjective)","Niveau de diplôme le plus élevé",rep("",3), "Classe d'âge",rep("",5),"Situation familiale",rep("",5),"Sexe",rep("",1),
                        #"Entourage au RSA",rep("",1),
                        "Année",rep("",4)
                        )) %>% setNames(c("Modèle logit", "Variable dépendante : se déclarer pauvre", "Odds ratio")) 

```

```{r, echo=FALSE}
#N = 13698 / R2 ajusté = 28.6
tab_final21_infminidecla <- run_regression(y="subj_inf_mini_decla", 
               x= c("quantile_nivie","revenus_locatifs","revenus_financiers","presta_rsa","presta_apl","presta_chomage","presta_handi",
                     "presta_etudes",
                    "statut_occup", "prof_statut_act","est_emploiprecaire", "diplome", "age_tranche","vie_fam", "sexe", #"conn_rsa",
                    "annee_fac"
), kable = FALSE) %>% 
  mutate(odds_ratio = ifelse(
    !is.na(valeur),paste0(gsub("\\.",",",odds),pvaleur),"Réf."
  )) %>% 
  dplyr::select(modalite_y,modalite,odds_ratio) %>% 
  slice(-1) %>% 
  # arrange(match(modalite, c(modalite[2],modalite[-2]))) %>% 
  # arrange(match(modalite, c(modalite[1:17],modalite[19],modalite[18],modalite[20:57]))) %>% 
  # arrange(match(modalite, c(modalite[1:20],modalite[22:24],modalite[21],modalite[25:57])))  %>% 
  # arrange(match(modalite, c(modalite[1:32],modalite[34],modalite[33],modalite[35:57]))) %>% 
  # arrange(match(modalite, c(modalite[1:36],modalite[38],modalite[37],modalite[39:57]))) %>% 
  # arrange(match(modalite, c(modalite[1:42],modalite[44],modalite[43],modalite[45:57]))) %>% 
  mutate(modalite_y = c("Niveau de vie",rep("",4),"Types de ressources ","perçues par le ménage ","(12 mois)",rep("",11),"Logement",rep("",2), "Situation professionnelle",rep("",9),"Précarité de l'emploi","(subjective)","Niveau de diplôme le plus élevé",rep("",3), "Classe d'âge",rep("",5),"Situation familiale",rep("",5),"Sexe",rep("",1),
                        #"Entourage au RSA",rep("",1),
                        "Année",rep("",4)
                        )) %>% setNames(c("Modèle logit", "Variable dépendante : se déclarer pauvre", "Odds ratio")) 


tab_final21 <- tab_final21_sentpauv %>% bind_cols(tab_final21_infminidecla %>% dplyr::select(`Odds ratio`)) %>% 
  setNames(c("Modèle logit","Odds ratio. Variables dépendantes :", "Se déclarer pauvre","Avoir un revenu inférieur au minimum déclaré"))

```



```{r, echo=FALSE}
tab_final21 <- tab_final21 %>% 
  kable(
    #caption="Modèle de synthèse des effets sur le sentiment de pauvreté et les difficultés financières perçues",
    booktabs = TRUE, longtable = TRUE) %>%
   kableExtra::column_spec(1, width = "3cm") %>% 
   kableExtra::column_spec(2, width = "5cm") %>% 
    kableExtra::column_spec(3:4, width = "3cm") %>%
  kableExtra::kable_styling(
  latex_options = c("hold_position", "repeat_header")#,
  #repeat_header_text = "\\textit{(suite)}",
  #repeat_header_continued = "\\textit{(suite en page suivante...)}"
  ) %>%
  kableExtra::pack_rows("Pauvreté monétaire", 1, 9) %>%
  kableExtra::pack_rows("Pauvreté institutionnelle", 10, 19) %>%
  kableExtra::pack_rows("Contrôles", 20, 57) 

tab_final21 %>% 
kableExtra::footnote(c("Sentiment de pauvreté : N = 13567 et $R^2$ ajusté = 25,9 \\\\, \\\\%","Difficultés financières perçues : N = 13698 et $R^2$ ajusté = 28,6 \\\\, \\\\%",
                          "* : significatif au seuil de $5 \\\\, \\\\%$ ; ** : $1 \\\\, \\\\%$ ; *** : $0,1 \\\\, \\\\%$."), escape = FALSE)  #%>% add_footnote_kable()
```


```{r, echo = FALSE, eval = FALSE}
# Ancien tableau 1
is_html <- knitr::is_html_output()
is_latex <- knitr::is_latex_output()
add_footnote_perso <- function(x, options, envir = "figure", remove_envir = TRUE){
  if(is_latex){
    res <-  add_footnote_latex(x, options, envir = envir, remove_envir = remove_envir)
  }else if(is_html){
    res <-  add_footnote_html(x, options)
  }else{
    res <-  x
  }
  res
}
add_footnote_kable <- function(x, options = knitr::opts_current$get()){
  if(length(grep("\\end{table}", x, fixed = TRUE)) >0){
    envir = "table"
    remove_envir = TRUE
  } else if(length(grep("\\end{longtable}", x, fixed = TRUE)) >0){
    envir = "longtable"
    remove_envir = FALSE
  } 
  x <- add_footnote_perso(x, options = options, envir = envir, remove_envir = remove_envir)
  class(x) <- "knitr_kable"
  if(is_latex){
    attr(x, "format") <- "latex"
  }else if(is_html){
    attr(x, "format") <- "html"
  }
  x
}

add_footnote_latex <- function(x, options, envir = "figure", remove_envir = TRUE){
  
  fin_envir <- sprintf("\\end{%s}", envir)
  if(length(grep(fin_envir, x, fixed = TRUE)) == 0){
    return(x)
  }
  
  params <- list(Source = list(),
                 Champ = list(),
                 Note = list(sep_multi = "\n\n"),
                 Lecture = list(prefix = "Note de lecture"))
  ajouts <- "\\footnotesize"
  for (opt in names(params)){
    ajouts <- add_fig_opt_latex(ajouts, options, opt,
                                prefix = params[[opt]]$prefix,
                                sep_multi = params[[opt]]$sep_multi,
                                sep_fichier = params[[opt]]$sep_fichier)
  }
  x <- paste0(x, ajouts, "\n\\normalsize")
  if(remove_envir){
    x <- sub(fin_envir, "", x, fixed = TRUE)
    x <- paste0(x, fin_envir)  
  }
  x  
}
add_fig_opt_latex <- function(x, options, nom_opt, 
                              prefix = nom_opt,
                              sep_multi = "---", sep_fichier = "\n\n"){
  if(is.null(prefix)){
    prefix <- nom_opt
  }
  if(is.null(sep_multi)){
    sep_multi <- "---"
  }
  if(is.null(sep_fichier)){
    sep_fichier <- "\n\n"
  }
  nom_opt_complet <- sprintf("fig.%s", tolower(nom_opt))
  opt <- options[[nom_opt_complet]]
  if(!is.null(opt)){
    x <- paste(x,
               latex_emph(prefix, opt, sep = sep_multi),
               sep = sep_fichier)
  }
  x
}
tab_compa <- readRDS("../rapport/figures/tab_compa.RDS")  %>% 
   kable(
     #caption="Réactualisation et réplication sur données plus récentes du modèle 1 de Duvoux et Papuchon (2018)",
        booktabs = TRUE, longtable = TRUE) %>%  
   kableExtra::column_spec(1, width = "3cm") %>% 
   kableExtra::column_spec(2, width = "5cm") %>% 
   kableExtra::column_spec(3:4, width = "2cm") %>%
 # kableExtra::row_spec(c(7,39,40), bold = T, background = "#fcdcf4") %>% 
 # kableExtra::row_spec(c(17,48,49), bold = T, background = "#e9c8e1") %>% 
kableExtra::kable_styling(
  latex_options = c("hold_position", "repeat_header"),
  repeat_header_text = "\\textit{(suite)}",
  repeat_header_continued = "\\textit{(suite en page suivante...)}"
  ) %>% 
    kableExtra::footnote(c("Modèle 2015-2017 : N = 8460 et $R^2$ ajusté = 24,8 \\\\, \\\\%","Modèle 2015-2019 : N = 13590 et $R^2$ ajusté = 25,5 \\\\, \\\\%.",
                           "* : significatif au seuil de $5 \\\\, \\\\%$ ; ** : $1 \\\\, \\\\%$ ; *** : $0,1 \\\\, \\\\%$."),
                         escape = FALSE) %>% add_footnote_kable()

tab_compa

```


\newpage

# Tableau 2

```{r, echo=FALSE}
#N = 13548 / R2 ajusté = 26.1 \%
tab_final21_sentpauv_bis <- run_regression(y="subj_pauvrete", 
               x= c("quantile_nivie","revenus_locatifs","revenus_financiers","presta_rsa","presta_apl","presta_chomage","presta_handi",
                    "presta_etudes",
                    "statut_occup", "prof_statut_act","est_emploiprecaire", "diplome", "age_tranche","vie_fam", "sexe",
                    #"conn_rsa", 
                    "conn_rsa_fam","conn_rsa_horsfam",
                    "annee_fac"
), kable = FALSE) %>% 
  mutate(odds_ratio = ifelse(
    !is.na(valeur),paste0(gsub("\\.",",",odds),pvaleur),"Réf."
  )) %>% 
  dplyr::select(modalite_y,modalite,odds_ratio) %>% 
  slice(-1) %>% 
  # arrange(match(modalite, c(modalite[2],modalite[-2]))) %>% 
  # arrange(match(modalite, c(modalite[1:17],modalite[19],modalite[18],modalite[20:57]))) %>% 
  # arrange(match(modalite, c(modalite[1:20],modalite[22:24],modalite[21],modalite[25:57])))  %>% 
  # arrange(match(modalite, c(modalite[1:32],modalite[34],modalite[33],modalite[35:57]))) %>% 
  # arrange(match(modalite, c(modalite[1:36],modalite[38],modalite[37],modalite[39:57]))) %>% 
  # arrange(match(modalite, c(modalite[1:42],modalite[44],modalite[43],modalite[45:57]))) %>% 
  mutate(modalite_y = c("Niveau de vie",rep("",4),"Types de ressources ","perçues par le ménage ","(12 mois)",rep("",11),"Logement",rep("",2), "Situation professionnelle",rep("",9),"Précarité de l'emploi","(subjective)","Niveau de diplôme le plus élevé",rep("",3), "Classe d'âge",rep("",5),"Situation familiale",rep("",5),"Sexe",rep("",1),
                        "Entourage au RSA",rep("",3),
                        "Année",rep("",4)
                        )) %>% setNames(c("Modèle logit", "Variable dépendante : se déclarer pauvre", "Odds ratio")) 

```

```{r, echo=FALSE}
#N = 13678 / R2 ajusté = 28.6 \%
tab_final21_infminidecla_bis <- run_regression(y="subj_inf_mini_decla", 
               x= c("quantile_nivie","revenus_locatifs","revenus_financiers","presta_rsa","presta_apl","presta_chomage","presta_handi",
                     "presta_etudes",
                    "statut_occup", "prof_statut_act","est_emploiprecaire", "diplome", "age_tranche","vie_fam", "sexe",
                    "conn_rsa_fam","conn_rsa_horsfam",
                    #"conn_rsa",
                    "annee_fac"
), kable = FALSE) %>% 
  mutate(odds_ratio = ifelse(
    !is.na(valeur),paste0(gsub("\\.",",",odds),pvaleur),"Réf."
  )) %>% 
  dplyr::select(modalite_y,modalite,odds_ratio) %>% 
  slice(-1) %>% 
  # arrange(match(modalite, c(modalite[2],modalite[-2]))) %>% 
  # arrange(match(modalite, c(modalite[1:17],modalite[19],modalite[18],modalite[20:57]))) %>% 
  # arrange(match(modalite, c(modalite[1:20],modalite[22:24],modalite[21],modalite[25:57])))  %>% 
  # arrange(match(modalite, c(modalite[1:32],modalite[34],modalite[33],modalite[35:57]))) %>% 
  # arrange(match(modalite, c(modalite[1:36],modalite[38],modalite[37],modalite[39:57]))) %>% 
  # arrange(match(modalite, c(modalite[1:42],modalite[44],modalite[43],modalite[45:57]))) %>% 
  mutate(modalite_y = c("Niveau de vie",rep("",4),"Types de ressources ","perçues par le ménage ","(12 mois)",rep("",11),"Logement",rep("",2), "Situation professionnelle",rep("",9),"Précarité de l'emploi","(subjective)","Niveau de diplôme le plus élevé",rep("",3), "Classe d'âge",rep("",5),"Situation familiale",rep("",5),"Sexe",rep("",1),
                        "Entourage au RSA",rep("",3),
                        "Année",rep("",4)
                        )) %>% setNames(c("Modèle logit", "Variable dépendante : se déclarer pauvre", "Odds ratio")) 


tab_final21_bis <- tab_final21_sentpauv_bis %>% bind_cols(tab_final21_infminidecla_bis %>% dplyr::select(`Odds ratio`)) %>% 
  setNames(c("Modèle logit","Odds ratio. Variables dépendantes :", "Se déclarer pauvre","Avoir un revenu inférieur au minimum déclaré"))

```



```{r, echo=FALSE}
tab_final21_bis <- tab_final21_bis %>% 
  slice(c(10:11),c(53:56)) %>% 
  kable(
    #caption="Modèle de synthèse des effets sur le sentiment de pauvreté et les difficultés financières perçues",
    booktabs = TRUE#,
    #longtable = TRUE
    ) %>%
   kableExtra::column_spec(1, width = "3cm") %>% 
   kableExtra::column_spec(2, width = "5cm") %>% 
    kableExtra::column_spec(3:4, width = "3cm") %>%
  kableExtra::kable_styling(
  latex_options = c("hold_position", "repeat_header"),
  repeat_header_text = "\\textit{(suite)}",
  repeat_header_continued = "\\textit{(suite en page suivante...)}"
   ) #%>%
  # kableExtra::pack_rows("Pauvreté monétaire", 1, 9) %>%
  # kableExtra::pack_rows("Pauvreté institutionnelle", 10, 19) %>%
  # kableExtra::pack_rows("Contrôles", 20, 57) 

tab_final21_bis %>% 
kableExtra::footnote(c("Sentiment de pauvreté : N = 13548 et $R^2$ ajusté = 26.1 \\\\, \\\\%","Difficultés financières perçues : N = 13678 et $R^2$ ajusté = 28,6 \\\\, \\\\%",
                          "* : significatif au seuil de $5 \\\\, \\\\%$ ; ** : $1 \\\\, \\\\%$ ; *** : $0,1 \\\\, \\\\%$."), escape = FALSE)  #%>% add_footnote_kable()
```

\newpage

# Tableau 3 ("insécurité" versus "infériorité")

```{r, echo=FALSE}
#Chargement de la base de données
bdd2018 <- read.csv(file="../data/2018/barometre2000_2018_diff.csv", sep=";", colClasses = "character", na.strings="") %>%
  filter(annee==2018)  #2018 uniquement (module spécial)

# Transformation de certaines variables en numérique
for(var in c("poids","sduc","sdrevcl","in11_1","in11_2","pe16")){ 
  bdd2018[[var]] <- as.numeric(gsub(",",".", bdd2018[[var]]))
}


revenus_a_imputer <- bdd2018 %>%
  mutate(sdrevcl = ifelse(sdrevcl==999999999,NA,sdrevcl)) %>%
  group_by(sdrevtr) %>% 
  summarise(sdrevcl = mean(sdrevcl,na.rm=TRUE))

bdd2018 <- bdd2018 %>% 
  mutate(
    sdrevcl_imput_moy = case_when(
      sdrevcl!=999999999 ~ sdrevcl,
      sdrevcl==999999999 & sdrevtr==1 ~ revenus_a_imputer$sdrevcl[1],
      sdrevcl==999999999 & sdrevtr==2 ~ revenus_a_imputer$sdrevcl[2],
      sdrevcl==999999999 & sdrevtr==3 ~ revenus_a_imputer$sdrevcl[3],
      sdrevcl==999999999 & sdrevtr==4 ~ revenus_a_imputer$sdrevcl[4],
      sdrevcl==999999999 & sdrevtr==5 ~ revenus_a_imputer$sdrevcl[5],
      sdrevcl==999999999 & sdrevtr==6 ~ revenus_a_imputer$sdrevcl[6],
      sdrevcl==999999999 & sdrevtr==7 ~ revenus_a_imputer$sdrevcl[7]
             )
  )  %>% 
   mutate(seuil_pauvrete = do.call(c,lapply(annee,function(annee_selec){
0.6*median(bdd2018[bdd2018$annee==annee_selec,"sdrevcl_imput_moy"]/bdd2018[bdd2018$annee==annee_selec,"sduc"],
           na.rm=TRUE)
}
))) %>% 
  mutate(subj_inf_mini_decla = factor(
     sdrevcl_imput_moy - ifelse(pe16==999999999,NA,pe16) <0,
     levels=c(TRUE,FALSE),
     labels=paste0("-",c("Rev. inf. au minimum décla.","Rev. sup. au minimum décla.")))
     ) %>%
  mutate(subj_pauvrete = 
           ifelse(pe3==3, TRUE,ifelse(pe3==4,NA,FALSE))) %>% 
  mutate(subj_risque_pauvrete = 
           ifelse(pe3==1, TRUE,ifelse(pe3==4,NA,FALSE))) %>% 
  mutate(subj_pauvrete_et_risque = 
           factor(
           ifelse(pe3==4, NA, ifelse(pe3==1,2,ifelse(pe3==2,1,3))),
           labels=c("Non pauvre","Risque pauvreté futur", "Déjà pauvre"))
         ) %>% 
  mutate(inf_besoin_aide_etat = 
           factor(
           ifelse(pe15==2, TRUE,ifelse(pe15==4,NA,FALSE)),
           labels=c("Être suffisamment aidé par les pouvoirs publics","Avoir besoin d’être aidé davantage par les pouvoirs publics"))
         ) %>% 
    mutate(inf_prof_souspayee = 
           factor(
           ifelse(in11_1<in11_2, TRUE,ifelse(in11_1==999999999 | in11_2==999999999 ,NA,FALSE)),
           labels=c("Les personnes qui ont la même profession ne devraient pas gagner plus","Les personnes qui ont la même profession devraient gagner plus"))
         ) %>%
    mutate(inf_integre =
           factor(
           ifelse(cs5_ab%in%c(3,4) | cs5_cd%in%c(3,4), TRUE,ifelse((cs5_ab=="5" & is.na(cs5_cd)) | (cs5_cd=="5" & is.na(cs5_ab)) ,NA,FALSE)),
          labels=c("Ne pas avoir le sentiment de ne pas être intégré dans la société","Avoir le sentiment de ne pas être intégré dans la société"))
         ) %>%
      mutate(inf_declassement_intergenerationnel = 
           factor(
           ifelse(og2%in%c(4,5), TRUE,ifelse(og2==6,NA,FALSE)),
           labels=c("Ne dirait pas que sa situation actuelle moins bonne que la situation de ses parents au même âge","Dirait que sa situation actuelle moins bonne que la situation de ses parents au même âge"))
         ) %>%
  mutate(ins_grave_pb_perso = 
           factor(
           ifelse(me1%in%c(3,4), TRUE,ifelse(me1==5,NA,FALSE)),
           labels=c("Ne pas pouvoir compter sur quelqu'un en cas de grave problème personnel","Pouvoir compter sur quelqu'un en cas de grave problème personnel"))
         ) %>%
   mutate(ins_diff_boucler_fin_mois = 
           factor(
           ifelse(me2%in%c(1,2), TRUE,ifelse(me2==5,NA,FALSE)),
           labels=c("Ne pas avoir de difficultés à boucler ses fins de mois","Avoir des difficultés à boucler ses fins de mois"))
         ) %>%
  mutate(ins_faire_face_dep_imprevue = 
           factor(
           ifelse(me3%in%c(2,3), TRUE,ifelse(me3==4,NA,FALSE)),
           labels=c("Ne pas avoir du mal à faire face à une dépense imprévue de 500 euros dans l'année qui vient","Avoir du mal à faire face à une dépense imprévue de 500 euros dans l'année qui vient"))
         ) %>% 
    mutate(ins_inquiet_sante = 
           factor(
           ifelse(me4%in%c(1,2), TRUE,ifelse(me4==5,NA,FALSE)),
           labels=c("Non inquiet à l’idée de ne pas pouvoir être bien soigné en cas de gros problème de santé","Inquiet à l’idée de ne pas pouvoir être bien soigné en cas de gros problème de santé"))
         ) %>% 
    mutate(ins_revenus_instables = 
           factor(
           ifelse(me5%in%c(2), TRUE,ifelse(me5==3,NA,FALSE)),
           labels=c("Revenus stables d'un mois sur l'autre","Revenus instables d'un mois sur l'autre"))
         ) %>% 
    mutate(ins_revenus_vont_diminuer = 
           factor(
           ifelse(me6%in%c(2), TRUE,ifelse(me6==4,NA,FALSE)),
           labels=c("Ne pense pas que les revenus du foyers vont diminuer dans les prochains mois","Pense que les revenus du foyers vont diminuer dans les prochains mois"))
         ) %>% 
  mutate(obj_pauvrete= sdrevcl_imput_moy/sduc<seuil_pauvrete) %>% 
  mutate(nivie = sdrevcl_imput_moy/sduc) %>% 
  mutate(quantile_nivie = factor(
    cut(sdrevcl_imput_moy/sduc, include.lowest=TRUE,
        breaks=quantile(sdrevcl_imput_moy/sduc,
                        probs=seq(0,1,0.2),na.rm=TRUE),
        labels=1:5),
    levels=c(2,1,3,4,5),
    labels=paste0("-Quintile ",c(2,1,3,4,5)))
  ) %>% 
  mutate(pauvrete_mon_rel= factor(
    ifelse(sdrevcl_imput_moy/sduc<seuil_pauvrete,3,
                                  ifelse(sdrevcl_imput_moy/sduc>=1.2*seuil_pauvrete,1,
                                         ifelse(sdrevcl_imput_moy/sduc<1.2*seuil_pauvrete &
                                                  sdrevcl_imput_moy/sduc>=seuil_pauvrete ,
                                                2,NA)
                                  )),
    levels=c(1,2,3),
    labels=paste0("-",c("Revenus > 20 pourcents seuil pauvreté",
                        "Entre le seuil et 20 pourcents au dessus",
                        "Pauvreté monétaire"))
  )
  )

```

<!-- Que signifie "se sentir pauvre" ? -->

<!-- 1. *Duvoux et Papuchon*  : **insécurité sociale** = déficit de garantie face à l'avenir. incertitude face à  la capacité d'assurer sa subsistance et donc son statut social. -->
<!--   * Mesure 1 : Ne pas pouvoir compter sur quelqu'un en cas de grave problème personnel (me1, module 2018) -->
<!--   * Mesure 2 : Avoir des difficultés à boucler ses fins de mois (me2, module 2018) -->
<!--   * Mesure 3 : Avoir du mal à faire face à une dépense imprévue de 500 euros dans l'année qui vient (me3, module 2018) -->
<!--   * Mesure 4 : Être inquiet à l’idée de ne pas pouvoir être bien soigné en cas de gros problème de santé (me4, module 2018) -->
<!--   * Mesure 5 : Avoirs des revenus instables d'un mois sur l'autre (me5, module 2018) -->
<!--   * Mesure 6 : Penser que les revenus du foyers vont diminuer dans les prochains mois (me6, module 2018) -->

<!-- 2. *Paugam* : **infériorité sociale** "manque de reconnaissance dans les différentes sphères de la vie sociale que l’on peut résumer par le sentiment de ne « compter pour » personne.". Ne se mesure pas directement dans le baromètre mais peut s'approcher par des proxys -->
<!--    * Mesure 1 : Ne pas se sentir suffisamment aidé par les pouvoirs publics (pe15, années paires) -->
<!--    * Mesure 2 : Trouver que les personnes qui ont la même profession devraient gagner plus (in11) -->
<!--    * Mesure 3 : Avoir le sentiment de ne pas être intégré dans la société (cs5_ab et cs5_cd) -->
<!--    * Mesure 4 : Avoir le sentiment d'avoir une moins bonne situation que ses parents au même âge (og2) -->





<!-- INSECURITE -->

<!-- ME1 filtre : non 2018 -->
<!-- Pensez-vous pouvoir compter sur quelqu’un en cas de grave problème personnel ? -->
<!-- 1. Oui, certainement -->
<!-- 2. Oui, probablement -->
<!-- 3. Non probablement pas -->
<!-- 4. Non, certainement pas -->
<!-- 5. [NSP] -->

<!-- ME2 filtre : non 2018 -->
<!-- Compte tenu de vos ressources, diriez-vous que votre ménage a des difficultés pour boucler ses -->
<!-- fins de mois ... ? -->
<!-- 1. Souvent -->
<!-- 2. De temps en temps -->
<!-- 3. Rarement -->
<!-- 4. Jamais -->
<!-- 5. [NSP] -->


<!-- ME3 Filtre : non 2018 -->
<!-- En imaginant que vous deviez faire face à une dépense imprévue de 500 € dans l’année qui vient, -->
<!-- pensez-vous... ? -->
<!-- 1. Que vous y feriez face sans trop de problème -->
<!-- 2. Qu’il vous serait assez difficile d’y faire face -->
<!-- 3. Qu’il vous serait très difficile d’y faire face -->
<!-- 4. [NSP] -->

<!-- ME4 filtre : non 2018 -->
<!-- Êtes-vous inquiet.e à l’idée de ne pas pouvoir être bien soigné en cas de gros problème de santé ? -->
<!-- 1. Oui, très inquiet.e -->
<!-- 2. Oui, assez inquiet.e -->
<!-- 3. Non, pas très inquiet.e -->
<!-- 4. Non, pas inquiet.e du tout -->
<!-- 5. [NSP] -->

<!-- ME5 filtre : non 2018 -->
<!-- Globalement, diriez-vous que les revenus de votre foyer sont plutôt variables ou plutôt stables d’un -->
<!-- mois sur l’autre ? -->
<!-- 1. Plutôt stables -->
<!-- 2. Plutôt variables -->
<!-- 3. [NSP] -->

<!-- ME6 filtre : non 2018 -->
<!-- Dans les mois qui viennent, pensez-vous que les revenus de votre foyer vont... ? -->
<!-- 1. Plutôt augmenter -->
<!-- 2. Plutôt diminuer -->
<!-- 3. Rester stables -->
<!-- 4. [NSP] -->

<!-- INFERIORITE  -->

<!-- PE15 Filtre : non MODULE ANNEES PAIRES 2014 - -->
<!-- Actuellement, compte tenu de votre situation globale, du montant des aides publiques (RSA, -->
<!-- allocations familiales, aides au logement), et du montant de vos impôts, vous considérez que : -->
<!-- 1. Vous êtes suffisamment aidé.e par les pouvoirs publics, ou n’avez pas besoin d’être aidé.e -->
<!-- 2. Vous auriez besoin d’être aidé.e davantage par les pouvoir publics -->
<!-- 3. [Non concerné.e] -->
<!-- 4. [NSP] -->

<!-- IN11filtre : ne pas poser aux étudiants, inactifs... SOCLE 2014 - -->
<!-- _1 Que gagnent en moyenne les gens qui ont la même profession que vous ? -->
<!-- \__________/ -->
<!-- _2 Que devraient gagner en moyenne les gens qui ont la même profession que vous ? -->
<!-- \__________/ -->

<!-- CS5_AB filtre : si sdsplit = 1 ou 2 SOCLE 2014 - -->
<!-- Avez-vous le sentiment d’être intégré.e dans la société française ? -->
<!-- 1. Très bien intégré.e -->
<!-- 2. Assez bien intégré.e -->
<!-- 3. Pas bien intégré.e -->
<!-- 4. Pas intégré.e du tout -->
<!-- 5. [NSP] -->
<!-- ENQUETEUR : PRÉSENTEZ LA LISTE – UNE SEULE RÉPONSE -->
<!-- CS5_CD filtre : si sdsplit = 3 ou 4 2018 -->
<!-- Avez-vous le sentiment d’être intégré.e dans la société ? -->
<!-- 1. Très bien intégré.e -->
<!-- 2. Assez bien intégré.e -->
<!-- 3. Pas bien intégré.e -->
<!-- 4. Pas intégré.e du tout -->
<!-- 5. [NSP] -->
<!-- ENQUETEUR : PRÉSENTEZ LA LISTE – UNE SEULE RÉPONSE -->


<!-- OG2 filtre : non SOCLE 2017 - -->
<!-- Par rapport à la situation de vos parents au même âge, diriez-vous que votre situation actuelle -->
<!-- est... ? -->
<!-- 1. Bien meilleure -->
<!-- 2. Plutôt meilleure -->
<!-- 3. À peu près identique -->
<!-- 4. Plutôt moins bonne -->
<!-- 5. Bien moins bonne -->
<!-- 6. [NSP] -->





<!-- NON TRAITES A CE STADE -->

<!-- - optimisme face à l’avenir -->
<!-- - vision sur l’évolution passée et à venir des inégalités, de la pauvreté et l’exclusion. -->


<!-- PE6 Filtre : non MODULE ANNEES PAIRES 2000 - -->
<!-- Voici un certain nombre de raisons qui peuvent expliquer que des personnes se trouvent en -->
<!-- situation d'exclusion ou de pauvreté. Pour chacune d'entre elles, dites-moi si vous êtes tout à fait -->
<!-- d’accord, plutôt d'accord, plutôt pas d'accord ou pas du tout d’accord. Si des personnes se -->
<!-- trouvent en situation d'exclusion ou de pauvreté, c'est parce qu'... ? -->
<!-- 1. Tout à fait d'accord -->
<!-- 2. Plutôt d'accord -->
<!-- 3. Plutôt pas d'accord -->
<!-- 4. Pas du tout d'accord -->
<!-- 5. [NSP] -->
<!-- ENQUETEUR : MONTRER ECRAN ET ENUMERER- UNE SEULE REPONSE – ROTATION DES ITEMS -->
<!-- _1 Elles ne veulent pas travailler -->
<!-- _2 Elles manquent de qualifications, de diplômes, pour trouver ou retrouver un emploi -->
<!-- _3 Elles n'ont pas eu de chance -->
<!-- _4 Il n'y a plus assez de travail pour tout le monde -->

<!-- SA6_AB filtre : sdsplit = 1 ou 2 SOCLE 2000 - -->
<!-- Êtes-vous d'accord ou pas avec les opinions suivantes ? En France … -->
<!-- 1. Plutôt d'accord -->
<!-- 2. Plutôt pas d'accord -->
<!-- 3. [NSP] -->
<!-- _1 Tout le monde peut être soigné quel que soit son revenu -->
<!-- _2 On a la même qualité de soins quel que soit son revenu -->
<!-- _3 Tout le monde peut être soigné quel que soit le lieu où il habite 2010 - -->
<!-- _4 On a la même qualité de soins quel que soit le lieu où l'on habite -->
<!-- _5 Les délais d'attente pour se faire soigner ne dépendent pas du revenu 2010 – -->
<!-- _6 Les délais d'attente pour se faire soigner ne dépendent pas du lieu où l'on habite 2010 - -->

<!-- CS1 filtre : non SOCLE 2014 - -->
<!-- Selon vous, la cohésion sociale en France est-elle actuellement : -->
<!-- 1. Très forte -->
<!-- 2. Assez forte -->
<!-- 3. Pas très forte -->
<!-- 4. Pas du tout forte -->
<!-- 5. [NSP] -->

<!-- Selon vous, comment la solidarité entre les générations a-t-elle évolué au cours des dix dernières -->
<!-- années ? -->
<!-- 1. Elle a augmenté -->
<!-- 2. Elle a diminué -->
<!-- 3. Elle n’a ni augmenté ni diminué -->
<!-- 4. [NSP] -->

<!-- CS18 filtre : non SOCLE 2015 - -->
<!-- Estimez-vous que les pouvoirs publics font trop, font ce qu'ils doivent ou ne font pas assez pour -->
<!-- les plus démunis ? -->
<!-- 1. Les pouvoirs publics font trop -->
<!-- 2. Les pouvoirs publics font ce qu'ils doivent -->
<!-- 3. Les pouvoirs publics ne font pas assez pour les plus démunis -->
<!-- 4. [NSP] -->

<!-- CS22 filtre : non SOCLE 2017 - -->
<!-- Selon vous, entre quels types de groupes les tensions seront-elles les plus fortes à l’avenir ? -->
<!-- 1. Entre les différentes générations -->
<!-- 2. Entre les différentes catégories socio-économiques -->
<!-- 3. Entre les différents partis ou tendances politiques -->
<!-- 4. Entre les différents territoires -->
<!-- 5. Entre les différentes confessions religieuses -->
<!-- 6. Entre les personnes d’origines différentes -->
<!-- 7. [NSP] -->

```{r, echo=FALSE}
var_subj <- c("subj_pauvrete_et_risque")
var_inf <- colnames(bdd2018)[which(substr(colnames(bdd2018),1,4)=="inf_")]
var_ins <- colnames(bdd2018)[which(substr(colnames(bdd2018),1,4)=="ins_")]
```

```{r, fig.width = 7.5,fig.height = 4, echo=FALSE, eval=FALSE}
bdd2018_small <- bdd2018 %>% dplyr::select(var_subj,var_inf,var_ins) %>% 
  mutate_all(as.numeric)

mat = cor(bdd2018_small %>% na.omit(), method = "spearman")
ordre = c(var_subj,var_inf,var_ins)
seuilcroix = 0.3

mat <- mat[ordre,ordre]
#mat[lower.tri(mat)] <- NA
gg_corrplot <- cbind(
  data.frame(mat)  %>%
    rownames_to_column(var="mesure1") %>%
    tidyr::pivot_longer(-mesure1, names_to="mesure2") %>%
    mutate(mesure1 = factor(mesure1,levels = unique(mesure1)),
           mesure2 = factor(mesure2,levels = levels(mesure1)),
          # mesure1 = factor(mesure1, labels=c("(-) Niveau\nde vie", "(-) Revenus\nlocatifs", "(-) Revenus\nfinanciers", "Sentiment de\npauvreté", "Difficultés\n financières\nperçues", "RSA", "APL", "HLM", "Chômage", "Bourse d'étude", "Handicap/\nDépendance")),
          # mesure2 = factor(mesure2,labels=levels(mesure1))
    ),
  data.frame(ggcorrplot::cor_pmat(mat))  %>%
    rownames_to_column(var="mesure1") %>%
    tidyr::pivot_longer(-mesure1, names_to="mesure2") %>%
    mutate(value=ifelse(value>0.05,1,2)) %>% 
    dplyr::select(value) %>% 
    setNames("signi")
)  %>% 
  mutate(label = round(value,2)) %>% 
  mutate(highval = ifelse(abs(value)>seuilcroix,2,1)) %>% 
  ggplot() + ## to get the rect filled
  geom_tile(aes(x=mesure1, y=mesure2), color="white", fill="white") +
  geom_point(aes(x=mesure1, y=mesure2, fill=value, stroke= highval),size = 5, shape=21) +
 # geom_point(aes(x=mesure1, y=mesure2, shape = highval),size = 2,color = "black")+
  labs(x = NULL, y = NULL, fill = "Corrélation Spearman") +
  theme_classic()+
  #scale_shape_manual(name=paste0("Corrélation > ",seuilcroix),values=c(4,NA), breaks=c("1","0"),labels=c("Oui","Non"))+
    continuous_scale("stroke", "stroke", name= paste0("Corrélation (val.\nabs.) > ",seuilcroix),
                   palette = function(x){scales::rescale(x, c(1, 2))},
                   breaks = c(2, 1), labels=c("Oui","Non")) +
  scale_fill_gradient(low="#FBFEF9",high="#E46726",
                        limits=c(0,1), na.value="#FFFFFF")  +
  scale_x_discrete(expand=c(0.05,0.05)) +
  scale_y_discrete(expand=c(0.05,0.05)) +
  scale_size(range=c(4,10), guide=NULL) +
   geom_rect(data=data.frame(x1=c(0.5,0.5), x2=c(1.5,1.5), y1=c(1.5,5.5), y2=c(5.5,11.5), t=c('Infériorité','Insécurité')), mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2, linetype=t), color="black", size=1, fill=NA) +
  scale_linetype_manual(name="Interprétation du sentiment de pauvreté", breaks=c('Infériorité','Insécurité'), values=c("dotted","solid")) +
 theme(axis.text.x = element_text(angle = 45, hjust=1))  

gg_corrplot
 
```

Part des personnes concernées par des situations d'insécurité ou infériorité en fonction de leur sentiment de pauvreté (%)

```{r, echo=FALSE}
fig <- bdd2018 %>%
  filter(!is.na(subj_pauvrete_et_risque)) %>% 
  group_by(subj_pauvrete_et_risque)
tableauX <- NULL
for(var in c(var_ins, var_inf)){
  moda <- levels(fig[[var]])[2]
  fig2 <- fig %>%
    mutate(variable = get(var)) %>% 
    summarise(variable = round(100*weighted.mean(ifelse(variable==moda,1,0),poids, na.rm=TRUE))
              ) %>% 
    setNames(c("subj_pauvrete_et_risque",moda))
  tableauX <- rbind(tableauX,c(moda,t(fig2)[-1,]))
    
}

tableauX <- data.frame(tableauX) %>% 
  setNames(c("","Non pauvre","Risque pauvreté futur", "Déjà pauvre")) %>%  
kable(format = 'latex',
      #caption= "Part des personnes concernées par des situations d'insécurité ou infériorité en fonction de leur sentiment de pauvreté (%)",
      booktabs = FALSE, longtable = FALSE)  %>%  
             kableExtra::column_spec(1, width = "6cm") %>% 
             kableExtra::column_spec(2:4, width = "2cm") %>% 
 kableExtra::footnote(c("Champ : Baromètre 2018", "Note : Les questions du Baromètre d'opinion qui correspondent aux lignes","du tableau correspondent, dans l'ordre,", "aux questions ME1, ME2, ME3, ME4, ME5, ME6, PE15, IN11, CS5 et OG2."), escape = FALSE)

tableauX

```

# Figure 3

```{r corrplot, echo=FALSE, fig.width=7, fig.height=5}
# library(ggnewscale)
# gg_corrplot <- readRDS("../rapport/figures/gg_corrplot.RDS")

bdd_poLCA <- bdd_logit %>% 
  mutate(s_sentpauvrisque = as.numeric(subj_pauvrete_et_risque),
         s_infminidecla = ifelse(as.numeric(subj_inf_mini_decla)==2,1,2),
         #m_quantilenivie = as.numeric(quantile_nivie),
         m_quantilenivie = as.numeric(substr(quantile_nivie,11,11)),
         # m_quantilenivie_inv = 6-as.numeric(quantile_nivie),
         m_quantilenivie_inv = 6-as.numeric(substr(quantile_nivie,11,11)),
         m_locatif = as.numeric(revenus_locatifs),
         m_locatif_inv = 3-as.numeric(revenus_locatifs),
         m_financier = as.numeric(revenus_financiers),
         m_financier_inv = 3-as.numeric(revenus_financiers),
         i_log = as.numeric(presta_apl),
         i_rsa = as.numeric(presta_rsa),
         i_chom = as.numeric(presta_chomage),
         i_handi = as.numeric(presta_handi),
         i_bourse = as.numeric(presta_etudes),
         i_hlm = as.numeric(presta_hlm),
  ) %>% 
  dplyr::select(ident, s_sentpauvrisque, s_infminidecla,
m_quantilenivie_inv, m_locatif_inv, m_financier_inv,
i_log, i_rsa, i_chom, i_handi, i_bourse, i_hlm, sexe)

bdd_poLCA_small <- bdd_poLCA %>% 
  dplyr::select(s_sentpauvrisque, s_infminidecla,
m_quantilenivie_inv, m_locatif_inv, m_financier_inv,
i_log, i_rsa, i_chom, i_handi, i_bourse, i_hlm)

mat = cor(bdd_poLCA_small %>% na.omit(), method = "spearman")
ordre = c("m_quantilenivie_inv","m_locatif_inv","m_financier_inv","s_sentpauvrisque", "s_infminidecla", "i_rsa", "i_log","i_hlm","i_chom","i_bourse","i_handi")
seuilcroix = 0.3

mat <- mat[ordre,ordre]
#mat[lower.tri(mat)] <- NA
gg_corrplot <- cbind(
  data.frame(mat)  %>%
    rownames_to_column(var="mesure1") %>%
    tidyr::pivot_longer(-mesure1, names_to="mesure2") %>%
    mutate(mesure1 = factor(mesure1,levels = unique(mesure1)),
           mesure2 = factor(mesure2,levels = levels(mesure1)),
           mesure1 = factor(mesure1, labels=c("(-) Niveau\nde vie", "(-) Revenus\nlocatifs", "(-) Revenus\nfinanciers", "Sentiment de\npauvreté", "Difficultés\n financières\nperçues", "RSA", "APL", "HLM", "Chômage", "Bourse d'étude", "Handicap/\nDépendance")),
           mesure2 = factor(mesure2,labels=levels(mesure1))
    ),
  data.frame(ggcorrplot::cor_pmat(mat))  %>%
    rownames_to_column(var="mesure1") %>%
    pivot_longer(-mesure1, names_to="mesure2") %>% #names_to : new 08/05
    mutate(value=ifelse(value>0.05,1,2)) %>% 
    dplyr::select(value) %>% 
    setNames("signi")
)  %>% 
  mutate(label = round(value,2)) %>% 
  mutate(highval = ifelse(abs(value)>seuilcroix,2,1)) %>% 
  ggplot() + ## to get the rect filled
  geom_tile(aes(x=mesure1, y=mesure2), color="white", fill="white") +
  geom_point(aes(x=mesure1, y=mesure2, fill=value, stroke= highval),size = 5, shape=21) +
 # geom_point(aes(x=mesure1, y=mesure2, shape = highval),size = 2,color = "black")+
  labs(x = NULL, y = NULL, fill = "Corrélation Spearman") +
  theme_classic()+
  #scale_shape_manual(name=paste0("Corrélation > ",seuilcroix),values=c(4,NA), breaks=c("1","0"),labels=c("Oui","Non"))+
    continuous_scale("stroke", "stroke", name= paste0("Corrélation (val.\nabs.) > ",seuilcroix),
                   palette = function(x){scales::rescale(x, c(1, 2))},
                   breaks = c(2, 1), labels=c("Oui","Non")) +
  #scale_fill_gradient(low="#FBFEF9",high="#E46726",
  #                      limits=c(0,1), na.value="#FFFFFF")  +
  scale_fill_gradient(low="#FFFFFF",high="#000000",
                        limits=c(0,1), na.value="#FFFF00")  +
  scale_x_discrete(expand=c(0.05,0.05)) +
  scale_y_discrete(expand=c(0.05,0.05)) +
  scale_size(range=c(4,10), guide=NULL) +
  geom_rect(data=data.frame(x1=c(0.5,3.5,5.5), x2=c(3.5,5.5,11.5), y1=c(0.5,3.5,5.5), y2=c(3.5,5.5,11.5), t=c('Monétaire','Subjective','Institutionnelle')), mapping=aes(xmin=x1, xmax=x2, ymin=y1, ymax=y2, linetype=t), color="black", size=1, fill=NA) +
  scale_linetype_manual(name="Dimension de la pauvreté", breaks=c("Monétaire","Subjective","Institutionnelle"), values=c("dotted","dashed", "solid")) +
 theme(axis.text.x = element_text(angle = 45, hjust=1))  

gg_corrplot
```

# Figure 4


```{r afe, echo=FALSE, fig.width=7, fig.height=5, out.width="100%"}
bdd_poLCA_poly <- polychoric(bdd_poLCA_small, smooth = TRUE, global=FALSE)

#Analyse en facteurs
pauvFA2 <- fa(bdd_poLCA_poly$rho, nfactors = 2, rotate = "oblimin", fm = "ml", cor="poly", scores= "regression", missing = TRUE, impute = "median") 

gg_loadings <- ggplot(data.frame(pauvFA2$loadings[,1:2]) %>%
                        mutate(Variable=c("Sentiment de pauvreté","Difficultés\nfinancières\nperçues","(-) Niveau de vie", "(-) Revenus locatifs", "(-) Revenus financiers", "APL", "RSA","Chômage","Handicap/Dépendance","Bourse d'étude","HLM")) %>% 
                        mutate(dimension = c(rep("Subjective",2),rep("Monétaire",3),rep("Institutionnelle",6))) %>% 
                        mutate(groupe = c(rep("Monétaire et Subjective",5),rep("Institutionnelle",6)))
                        ,aes(x=ML2,y=ML1)) +
  geom_vline(xintercept = 0, color = "black", linetype = "dotted") +
  geom_hline(yintercept = 0, color = "black", linetype = "dotted") +
  stat_ellipse(aes(fill=factor(groupe)),type = "t", linetype = 1, cex=1, geom="polygon", alpha=0.5, level=0.8) +
 #geom_abline(intercept = 0, slope = 1, color="black", linetype="solid") +
 geom_vline(xintercept = 0.25, color="black", linetype="solid") +
  geom_point(aes(shape=factor(dimension)), color="black", cex=3) +
  ggrepel::geom_text_repel(aes(label=Variable),size=3,nudge_y=0.00)+
  ggrepel::geom_label_repel(data = data.frame(x=c(0.0719,0.5),
           y=c(0.533,0.5)),aes(x=x,y=y), #Vérifier
           label = c("Pauvreté\ninstitutionnelle","Pauvretés monétaire\net subjective"),
           min.segment.length = 0, size=4, fontface="bold",
           nudge_x=c(0.3,0), nudge_y=c(0.3,0.4), seed=1) + 
   xlab("Saturation sur le premier facteur (20,9 %)") +
  ylab("Saturation sur le second facteur (19,2 %)") + 
  scale_fill_manual(values=c("grey80","grey80")) +
  scale_shape_manual(name="Dimension de la pauvreté", values=c(16,17,18))+
  guides(fill="none") +
  theme_minimal()

gg_loadings

```

\newpage

# Figure 5A 

```{r, echo=FALSE}
actives_autres <- c("quantile_nivie","revenus_financiers","revenus_locatifs","presta_rsa","presta_chomage","presta_apl","presta_handi","presta_etudes", "presta_hlm")
actives_subj <- c("subj_pauvrete_et_risque", "subj_inf_mini_decla")
actives <- c(actives_subj,actives_autres)
passives <- c("statut_occup", "diplome", "conn_rsa","annee_fac", "prof_statut_act", "age_tranche","vie_fam"#,"presta_handi",
              )

num_indiv <- bdd_logit %>% 
  dplyr::select(c(all_of("ident"),all_of(actives),all_of(passives))) %>% 
  tidyr::drop_na() %>% dplyr::select(ident) %>% pull()

bdd_CFA_rmnasup  <- bdd_logit %>% 
  mutate(s_sentpauvrisque = as.numeric(subj_pauvrete_et_risque),
         s_infminidecla = ifelse(as.numeric(subj_inf_mini_decla)==2,1,2),
         m_quantilenivie = as.numeric(substr(quantile_nivie,11,11)),
         m_quantilenivie_inv = 6-as.numeric(substr(quantile_nivie,11,11)),
         m_locatif = as.numeric(revenus_locatifs),
         m_locatif_inv = 3-as.numeric(revenus_locatifs),
         m_financier = as.numeric(revenus_financiers),
         m_financier_inv = 3-as.numeric(revenus_financiers),
         i_log = as.numeric(presta_apl),
         i_rsa = as.numeric(presta_rsa),
         i_chom = as.numeric(presta_chomage),
         i_handi = as.numeric(presta_handi),
         i_bourse = as.numeric(presta_etudes),
         i_hlm = as.numeric(presta_hlm),
         cov_sexe_femme = ifelse(sexe=="-Femme",1,0),
         cov_sexe_homme = ifelse(sexe=="-Homme",1,0),
         cov_statut_occup0_proprio = ifelse(statut_occup0=="-Propriétaire",1,0),
          cov_statut_occup0_locataire = ifelse(statut_occup0=="-Locataire ou hébergé",1,0),
         cov_diplome_sans = ifelse(diplome=="-CAP, BEP ou moins",1,0),
         cov_diplome_bac = ifelse(diplome=="-Baccalauréat",1,0),
         cov_diplome_bacplus2 = ifelse(diplome=="-Bac + 2",1,0), 
         cov_diplome_bacplus3 = ifelse(diplome=="-Bac + 3 ou plus",1,0),
         cov_prof_statut_act_inter = ifelse(prof_statut_act=="-Profession intermédiaire",1,0),
         cov_prof_statut_act_chom = ifelse(prof_statut_act=="-Chômeur",1,0),
         cov_prof_statut_act_ouv = ifelse(prof_statut_act=="-Ouvrier",1,0),
         cov_prof_statut_act_commer = ifelse(prof_statut_act=="-Artisan commerçant",1,0),
         cov_prof_statut_act_employ = ifelse(prof_statut_act=="-Employé",1,0),
         cov_prof_statut_act_autrinac = ifelse(prof_statut_act=="-Autre inactif",1,0),
         cov_prof_statut_act_foyer = ifelse(prof_statut_act=="-Au foyer",1,0),
         cov_prof_statut_act_cadre = ifelse(prof_statut_act=="-Cadre supérieur, profession libérale",1,0),
         cov_prof_statut_act_retr = ifelse(prof_statut_act=="-Retraité",1,0),
         cov_prof_statut_act_agri = ifelse(prof_statut_act=="-Agriculteur",1,0),
         cov_prof_statut_act_commer = ifelse(prof_statut_act=="-Artisan commerçant",1,0),
         cov_age_tranche_1829 = ifelse(age_tranche=="-18 à 29 ans",1,0),
         cov_age_tranche_3039 = ifelse(age_tranche=="-30 à 39 ans",1,0),
         cov_age_tranche_4049 = ifelse(age_tranche=="-40 à 49 ans",1,0),
         cov_age_tranche_5059 = ifelse(age_tranche=="-50 à 59 ans",1,0),
         cov_age_tranche_6069 = ifelse(age_tranche=="-60 à 69 ans",1,0),
         cov_age_tranche_70 = ifelse(age_tranche=="-70 ans et plus",1,0),
         cov_vie_fam_mono = ifelse(vie_fam=="-Chef famille monoparentale",1,0),
         cov_vie_fam_seul = ifelse(vie_fam=="-Vit seul",1,0),
         cov_vie_fam_coupsansenf = ifelse(vie_fam=="-Membre du couple (pas d’enfants à charge)",1,0),
         cov_vie_fam_coupenf = ifelse(vie_fam=="-Membre du couple (enfants à charge)",1,0),
         cov_vie_fam_autre = ifelse(vie_fam=="-Autre situation familiale",1,0),
         cov_vie_fam_enf = ifelse(vie_fam=="-Enfant",1,0)
  ) %>%
  filter(ident%in%num_indiv) %>% 
  dplyr::select(s_sentpauvrisque, s_infminidecla,
m_quantilenivie_inv, m_locatif_inv, m_financier_inv,
i_log, i_rsa, i_chom, i_handi, i_bourse, i_hlm, cov_sexe_femme, cov_sexe_homme, cov_statut_occup0_locataire, cov_statut_occup0_proprio, cov_diplome_sans, cov_diplome_bac, cov_diplome_bacplus2, cov_diplome_bacplus3, cov_prof_statut_act_inter, cov_prof_statut_act_chom, cov_prof_statut_act_ouv, cov_prof_statut_act_commer, cov_prof_statut_act_employ, cov_prof_statut_act_autrinac, cov_prof_statut_act_foyer, cov_prof_statut_act_cadre, cov_prof_statut_act_retr, cov_prof_statut_act_agri, cov_prof_statut_act_commer, cov_age_tranche_1829, cov_age_tranche_3039, cov_age_tranche_4049, cov_age_tranche_5059, cov_age_tranche_6069, cov_age_tranche_70, cov_vie_fam_mono, cov_vie_fam_seul, cov_vie_fam_coupenf, cov_vie_fam_coupsansenf, cov_vie_fam_autre, cov_vie_fam_enf) %>% 
  mutate(s_sentpauvrisque_std = scale(s_sentpauvrisque))
```

```{r, echo=FALSE, eval=TRUE, include=FALSE}
pauv_model2_old <- '
s =~ s_sentpauvrisque + s_infminidecla
m =~ m_quantilenivie_inv + m_locatif_inv + m_financier_inv
i =~ i_rsa + i_chom + i_log + i_handi + i_bourse + i_hlm 
'
pauv_model2 <- '
s =~ s_sentpauvrisque + s_infminidecla
m =~ m_quantilenivie_inv + m_locatif_inv + m_financier_inv
i =~ i_rsa +  i_chom + i_log + i_handi + i_bourse + i_hlm
s_infminidecla ~~ m_quantilenivie_inv'


fit2_var <- lavaan::cfa(pauv_model2, data = bdd_CFA_rmnasup,
ordered = TRUE, orthogonal=FALSE,std.lv = TRUE) #estimator = "WLSMV"

semPaths(fit2_var, what = "est", edge.label.cex = 0.7,
edge.color = 1, esize = 1, sizeMan = 4.5, asize = 2.5,
intercepts = FALSE, rotation = 4, thresholdColor = "black",
mar = c(1, 5, 1.5, 5), fade = FALSE, nCharNodes = 4)

# fitMeasures
print("fit2_var: ")
fitMeasures(fit2_var)[c("chisq","df","pvalue","cfi","tli","rmsea", "srmr")]

```

```{r, echo=FALSE}
# Modèle 2 revu
grviz2 <- grViz("
digraph boxes_and_circles {
  
  # a 'graph' statement
  graph [overlap = true, fontsize = 20,rankdir = LR,
  bgcolor=transparent, splines=true]
  
   node [shape = circle, width=1.5,
        fontcolor=black, fixedsize=true, fontsize=25]
   subgraph {
    rank = same;
    I [label='Institutio.'];
    M [label='Monétaire'];
    S [label='Subjectif'];
   }
   
   # liens entre facteurs
  edge [shape = circle, alpha=1 color=black style=filled penwidth=1 arrowsize=.75 minlen=2]
  subgraph {
    rank = same;
  S -> M [label = 0.93 penwidth=1.15  dir=both color=black];
  M -> I [label = 0.94 penwidth=1.15  dir=both];
  S -> I [label = 0.78 penwidth=1.15  dir=both];
  }
  
  node [shape = box, fixedsize = true,width = 3, fontsize=20]
   subgraph {
    rank = same;
  2 [label='Diff. fin. perçues'];
  1 [label='Sentiment de pauvreté'];
  3 [label='(-) Quintile niveau de vie'];
  4 [label='(-) Revenus locatifs'];
  5 [label='(-) Revenus financiers'];
  6 [label='RSA'];
  7 [label='Chômage'];
  8 [label='APL'];
  9 [label='Hand./Dépend.'];
  10 [label='Bourse étude'];
  11 [label='HLM'];
   }
  
  # loadings
  I->6 [ label = 0.75 penwidth=1.15];
  I->7 [ label = 0.35 penwidth=1.15];
  I->8 [ label = 0.88 penwidth=1.15 color=black];
  I->9 [ label = 0.35 penwidth=1.15];
  I->10 [ label = 0.43 penwidth=1.15];
  I->11 [ label = 0.66 penwidth=1.15];
  M->3 [ label = 0.81 penwidth=1.15 color=black];
  M->4 [ label = 0.61 penwidth=1.15];
  M->5 [ label = 0.63 penwidth=1.15];
  S->1 [ label = 0.73 penwidth=1.15];
  S->2 [ label = 0.70 penwidth=1.15 color=black];
  
  # variances
  edge [shape = circle, alpha=.5 color=gray50 style=dashed penwidth=1.15 arrowsize=.75 minlen=2 dir=both]
  1:e -> 1:e [label = 0.46];
  2:e -> 2:e [label = 0.51];
  3:e -> 3:e [label = 0.34];
  2:e -> 3:e [label = 0.17];
  4:e -> 4:e [label = 0.62];
  5:e -> 5:e [label = 0.61];
  6:e -> 6:e [label = 0.44];
  7:e -> 7:e [label = 0.88];
  8:e -> 8:e [label = 0.22];
  9:e -> 9:e [label = 0.87];
  10:e -> 10:e [label = 0.81];
  11:e -> 11:e [label = 0.57];
  S -> S [label = 1.00];
  M -> M [label = 1.00];
  I -> I [label = 1.00];
  
  

  }
", height=600, width=600)
grviz2
```


\newpage

# Tableau 4

```{r,  include = FALSE}

pauv_model_mimic_inter_old <- '
m =~ m_quantilenivie_inv + m_locatif_inv + m_financier_inv
i =~ i_rsa + i_chom + i_log + i_handi + i_bourse + i_hlm 
m ~~ s_sentpauvrisque_std
i ~~ s_sentpauvrisque_std
# + Controles intermediaires : cf ci-dessous
'

pauv_model_mimic_inter <- '
s =~ s_sentpauvrisque + s_infminidecla
m =~ m_quantilenivie_inv + m_locatif_inv + m_financier_inv
i =~ i_rsa + i_chom + i_log + i_handi + i_bourse + i_hlm 
s_infminidecla ~~ m_quantilenivie_inv
m ~~ s
i ~~ s
# Controles intermediaires
i ~  cov_prof_statut_act_agri + cov_prof_statut_act_commer + cov_prof_statut_act_cadre + cov_prof_statut_act_employ + cov_prof_statut_act_ouv + cov_prof_statut_act_chom + 
cov_prof_statut_act_retr +  cov_prof_statut_act_foyer +
cov_prof_statut_act_autrinac + cov_diplome_sans + cov_diplome_bacplus2 + cov_diplome_bacplus3 + cov_age_tranche_1829 + cov_age_tranche_4049 + cov_age_tranche_5059 + cov_age_tranche_6069 + cov_age_tranche_70 +
cov_vie_fam_seul + cov_vie_fam_coupenf + cov_vie_fam_mono +
cov_vie_fam_enf   + cov_vie_fam_autre +  cov_sexe_homme
m ~  cov_prof_statut_act_agri + cov_prof_statut_act_commer + cov_prof_statut_act_cadre + cov_prof_statut_act_employ + cov_prof_statut_act_ouv + cov_prof_statut_act_chom + 
cov_prof_statut_act_retr +  cov_prof_statut_act_foyer +
cov_prof_statut_act_autrinac + cov_diplome_sans + cov_diplome_bacplus2 + cov_diplome_bacplus3 + cov_age_tranche_1829 + cov_age_tranche_4049 + cov_age_tranche_5059 + cov_age_tranche_6069 + cov_age_tranche_70 +
cov_vie_fam_seul + cov_vie_fam_coupenf + cov_vie_fam_mono +
cov_vie_fam_enf   + cov_vie_fam_autre +  cov_sexe_homme
s_sentpauvrisque_std ~  cov_prof_statut_act_agri + cov_prof_statut_act_commer + cov_prof_statut_act_cadre + cov_prof_statut_act_employ + cov_prof_statut_act_ouv + cov_prof_statut_act_chom + 
cov_prof_statut_act_retr +  cov_prof_statut_act_foyer +
cov_prof_statut_act_autrinac + cov_diplome_sans + cov_diplome_bacplus2 + cov_diplome_bacplus3 + cov_age_tranche_1829 + cov_age_tranche_4049 + cov_age_tranche_5059 + cov_age_tranche_6069 + cov_age_tranche_70 +
cov_vie_fam_seul + cov_vie_fam_coupenf + cov_vie_fam_mono +
cov_vie_fam_enf   + cov_vie_fam_autre +  cov_sexe_homme
'



fit_mimic_inter <- lavaan::cfa(pauv_model_mimic_inter, data = bdd_CFA_rmnasup,ordered=TRUE, orthogonal=FALSE,std.lv = TRUE)

sum2 <- summary(fit_mimic_inter, standardized = TRUE, fit.measures = TRUE)
```

```{r tab41,  echo=FALSE, eval=TRUE}
tab_covariates_inter_cfa <- sum2$pe %>% 
  filter(op=="~" & substr(rhs,1,3)=="cov") %>% 
  mutate(variable=gsub("cov_","",rhs),
         pvaleur=cut(pvalue, breaks = c(0, 0.001, 0.01, 0.05, 1),
                                      include.lowest = TRUE,
                                      labels = c('***', '**', '*', '')),
         estimateur=paste0(round(est,2),pvaleur) 
         ) %>% 
  dplyr::select(lhs,variable,estimateur) %>%
  pivot_wider(
    names_from = lhs,
    values_from = estimateur
  ) %>% dplyr::right_join(
    data.frame(variable = c("prof_statut_act_agri", "prof_statut_act_commer", "prof_statut_act_cadre", "prof_statut_act_inter", "prof_statut_act_employ", "prof_statut_act_ouv", "prof_statut_act_chom",
"prof_statut_act_retr", "prof_statut_act_foyer", "prof_statut_act_autrinac", "diplome_sans","diplome_bac", "diplome_bacplus2", "diplome_bacplus3", "age_tranche_1829","age_tranche_3039",
 "age_tranche_4049", "age_tranche_5059", "age_tranche_6069", "age_tranche_70", "vie_fam_seul", "vie_fam_coupsansenf", "vie_fam_coupenf",
 "vie_fam_mono", "vie_fam_enf", "vie_fam_autre","sexe_femme", "sexe_homme"),
	   libelle_mod = c("Agriculteur", "Artisan commerçant", "Cadre supérieur, profession libérale", "Profession intermédiaire", "Employé", "Ouvrier", "Chômeur", "Retraité",
"Au foyer", "Autre inactif", "CAP, BEP ou moins", "Baccalauréat", "Bac + 2", "Bac + 3 ou plus", "18 à 29 ans", "30 à 39 ans", "40 à 49 ans", "50 à 59 ans",
 "60 à 69 ans", "70 ans et plus", "Vit seul", "Membre du couple (pas d’enfants à charge)", "Membre du couple (enfants à charge)",
 "Chef famille monoparentale", "Enfant", "Autre situation familiale", "Femme", "Homme"),
           libelle_var=c("Situation professionnelle",rep("",9),"Niveau de diplôme le plus élevé",rep("",3), "Classe d'âge",rep("",5),"Situation familiale",rep("",5),"Sexe",rep("",1))
) ,
    by="variable")  %>% 
     arrange(match(variable,c("prof_statut_act_agri", "prof_statut_act_commer", "prof_statut_act_cadre", "prof_statut_act_inter", "prof_statut_act_employ", "prof_statut_act_ouv", "prof_statut_act_chom",
"prof_statut_act_retr", "prof_statut_act_foyer", "prof_statut_act_autrinac", "diplome_sans","diplome_bac", "diplome_bacplus2", "diplome_bacplus3", "age_tranche_1829","age_tranche_3039",
 "age_tranche_4049", "age_tranche_5059", "age_tranche_6069", "age_tranche_70", "vie_fam_seul", "vie_fam_coupsansenf", "vie_fam_coupenf",
 "vie_fam_mono", "vie_fam_enf", "vie_fam_autre","sexe_femme", "sexe_homme")))  %>% 
  dplyr::select(libelle_var,libelle_mod,m,i,s_sentpauvrisque_std)  %>% 
  replace(is.na(.), "Réf.") %>% 
  setNames(c("","Pauvreté...","Monétaire","Institutionnelle","Subjective"))
  # setNames(c("","Pauvreté...","Monétaire","Institutionnelle","Sentiment de pauvreté"))
 

  
```

```{r tab41b, eval=TRUE, echo=FALSE}

tab_covariates_inter_cfa %>%
  kable(
    #caption="Effets des covariables sur les différentes dimensions de la pauvreté",
    booktabs = TRUE, longtable = FALSE) %>%
   kableExtra::column_spec(1, width = "2.5cm") %>%
   kableExtra::column_spec(2, width = "4cm") %>%
   kableExtra::column_spec(3:5, width = "2.5cm") %>%
  kableExtra::kable_styling(
  latex_options = c("hold_position", "repeat_header"),
  repeat_header_text = "\\textit{(suite)}",
  repeat_header_continued = "\\textit{(suite en page suivante...)}"
  ) %>%
  kableExtra::footnote("* : significatif au seuil de 5 % ; ** : 1 % ; *** : 0,1 %.")

```


# Figure 5B

```{r, echo=FALSE, include = FALSE}
# pauv_model_hier3_var <- '
# m =~ 0.85*m_quantilenivie_inv + m_locatif_inv + m_financier_inv
# i =~  0.75*i_rsa +  i_chom + i_log + i_handi + i_bourse + i_hlm 
# pauvrete =~ NA*m + i + s_sentpauvrisque_std
# # Correction de la variance négative
# m ~~ 0.01*m
# pauvrete ~~ 1 * pauvrete
# '

# Modèle 4 revu
pauv_model_hier3_var <- '
m =~ 0.83*m_quantilenivie_inv + m_locatif_inv + m_financier_inv
i =~ 0.74*i_rsa +  i_chom + i_log + i_handi + i_bourse + i_hlm
pauvrete =~ NA*m + i + s_sentpauvrisque_std
# Correction de la variance négative
m ~~ 0.04*m
pauvrete ~~ 1 * pauvrete
'
pauv_model_hier3_var <- '
m =~ 0.83*m_quantilenivie_inv + m_locatif_inv + m_financier_inv
i =~ 0.74*i_rsa +  i_chom + i_log + i_handi + i_bourse + i_hlm
pauvrete =~ NA*m + i + s_sentpauvrisque_std
# Correction de la variance négative
m ~~ 0.04*m
pauvrete ~~ 1 * pauvrete
'

pauv_model_hier3_var <- '
s =~ 0.73*s_sentpauvrisque + s_infminidecla
m =~ 0.81*m_quantilenivie_inv + m_locatif_inv + m_financier_inv
i =~ 0.75*i_rsa +  i_chom + i_log + i_handi + i_bourse + i_hlm
s_infminidecla ~~ m_quantilenivie_inv
pauvrete =~ m + i + s
# Correction de la variance négative
pauvrete ~~ 1 * pauvrete
m ~~ 0.04*m

'


fit_hier3_var <- lavaan::cfa(pauv_model_hier3_var, data = bdd_CFA_rmnasup,
ordered = TRUE, orthogonal=TRUE, std.lv=FALSE)

semPaths(fit_hier3_var, what = "est", edge.label.cex = 0.7,
edge.color = 1, esize = 1, sizeMan = 4.5, asize = 2.5,
intercepts = FALSE, rotation = 4, thresholdColor = "black",
mar = c(1, 5, 1.5, 5), fade = FALSE, nCharNodes = 4)

# Pour m
#sqrt(0.830^2*0.284+0.597^2*0.629+0.597^2*0.629+0.04)
# Pour pvrt
#sqrt(0.93^2*?+1^2*?+0.65^2*0.58)


```




```{r, echo=FALSE}
grviz4 <- grViz("
digraph boxes_and_circles {
  
  # a 'graph' statement
  graph [overlap = true, fontsize = 20,rankdir = LR,
  bgcolor=transparent, splines=true]
  
   node [shape = circle, width=1.5,
        fontcolor=black, fixedsize=true, fontsize=25]
   subgraph {
    rank = same;
    P [label='Pauvreté'];
    }
   subgraph {
    rank = same;
    S [label='Subjectif'];
    M [label='Monétaire'];
    I [label='Institutio.'];
   }
   
  
  node [shape = box, fixedsize = true,width = 3, fontsize=20]
   subgraph {
   rank = same;
  
  1 [label='Sentiment de pauvreté'];
  2 [label='Diff. fin. perçues'];
  3 [label='(-) Quintile niveau de vie'];
  4 [label='(-) Revenus locatifs'];
  5 [label='(-) Revenus financiers'];
  6 [label='RSA'];
  7 [label='Chômage'];
  8 [label='APL'];
  9 [label='Hand./Dépend.'];
  10 [label='Bourse étude'];
  11 [label='HLM'];
  }
  
  # loadings
  
  I->6 [ label = 0.75 penwidth=1.15];
  I->7 [ label = 0.36 penwidth=1.15];
  I->8 [ label = 0.89 penwidth=1.15];
  I->9 [ label = 0.36 penwidth=1.15];
  I->10 [ label = 0.43 penwidth=1.15];
  I->11 [ label = 0.66 penwidth=1.15];

  M->3 [ label = 0.81 penwidth=1.15];
  M->4 [ label = 0.61 penwidth=1.15];
  M->5 [ label = 0.63 penwidth=1.15];
  
  S->1 [ label = 0.73 penwidth=1.15];
  S->2 [ label = 0.67 penwidth=1.15];
  
  P -> S [label = 0.89 penwidth=2.5];
  P -> I [label = 0.92 penwidth=2.5];
  P -> M [label = 1.00 penwidth=2.5];
  
  
  # variances
  edge [shape = circle, alpha=.5 color=gray50 style=dashed penwidth=1.15 arrowsize=.75 minlen=2 dir=both]
  1:e -> 1:e [label = 0.44];
  2:e -> 2:e [label = 0.53];
  3:e -> 3:e [label = 0.32];
  2:e -> 3:e [label = 0.21];
  4:e -> 4:e [label = 0.61];
  5:e -> 5:e [label = 0.59];
  6:e -> 6:e [label = 0.44];
  7:e -> 7:e [label = 0.88];
  8:e -> 8:e [label = 0.22];
  9:e -> 9:e [label = 0.87];
  10:e -> 10:e [label = 0.81];
  11:e -> 11:e [label = 0.57];
  S -> S [label = 0.25];
  M -> M [label = 0.04];
  I -> I [label = 0.14];
  P -> P [label = 1.00];

  }
", width=600,height=600) 

saveRDS(grviz4,"../rapport/figures/grviz4.RDS")

grviz4
```


\newpage 

# Tableau 5


```{r, include=FALSE}
pauv_model_mimic_global_old <- '
m =~ 0.83*m_quantilenivie_inv + m_locatif_inv + m_financier_inv
i =~ 0.74*i_rsa +  i_chom + i_log + i_handi + i_bourse + i_hlm
pauvrete =~ NA*m + i + s_sentpauvrisque_std


# Correction de la variance négative : cf. ci-dessous
# Controles globaux : cf. ci-dessous
'

pauv_model_mimic_global <- '
m =~ 0.81*m_quantilenivie_inv + m_locatif_inv + m_financier_inv
i =~ 0.75*i_rsa +  i_chom + i_log + i_handi + i_bourse + i_hlm
s =~ 0.73*s_sentpauvrisque + s_infminidecla
s_infminidecla ~~ m_quantilenivie_inv

pauvrete =~ NA*m + i + s


# Correction de la variance négative
m ~~ 0.04*m
pauvrete ~~ 1 * pauvrete


# Controles globaux
pauvrete ~  cov_prof_statut_act_agri + cov_prof_statut_act_commer + cov_prof_statut_act_cadre + cov_prof_statut_act_employ + cov_prof_statut_act_ouv + cov_prof_statut_act_chom + 
cov_prof_statut_act_retr +  cov_prof_statut_act_foyer +
cov_prof_statut_act_autrinac + cov_diplome_sans + cov_diplome_bacplus2 + cov_diplome_bacplus3 + cov_age_tranche_1829 + cov_age_tranche_4049 + cov_age_tranche_5059 + cov_age_tranche_6069 + cov_age_tranche_70 +
cov_vie_fam_seul + cov_vie_fam_coupenf + cov_vie_fam_mono +
cov_vie_fam_enf   + cov_vie_fam_autre +  cov_sexe_homme
'



fit_mimic_global <- lavaan::cfa(pauv_model_mimic_global, data = bdd_CFA_rmnasup,ordered=TRUE)

sum <- summary(fit_mimic_global, standardized = TRUE, fit.measures = TRUE)

f <- fitMeasures(fit_mimic_global)[c("chisq","df","cfi","rmsea", "srmr")]
f <- c(round(f[c("chisq","df")]), gsub("\\.",",", round(f[c("cfi","rmsea", "srmr")],3)))
names(f) <- c("chisq","df","cfi","rmsea", "srmr")
#R2_ajuste1 <- round(100*with(sum, 1 - deviance/null.deviance),1)," %"))
#N1 <- length(summary(reg1)$deviance.resid)

```

```{r, echo=FALSE, eval = TRUE}


tab_covariates_global_cfa <- sum$pe %>% 
  filter(op=="~" & substr(rhs,1,3)=="cov") %>% 
  mutate(variable=gsub("cov_","",rhs),
         pvaleur=cut(pvalue, breaks = c(0, 0.001, 0.01, 0.05, 1),
                                      include.lowest = TRUE,
                                      labels = c('***', '**', '*', '')),
         estimateur=paste0(round(est,2),pvaleur) 
         ) %>% 
  dplyr::select(lhs,variable,estimateur) %>%
  pivot_wider(
    names_from = lhs,
    values_from = estimateur
  ) %>% dplyr::right_join(
    data.frame(variable = c("prof_statut_act_agri", "prof_statut_act_commer", "prof_statut_act_cadre", "prof_statut_act_inter", "prof_statut_act_employ", "prof_statut_act_ouv", "prof_statut_act_chom",
"prof_statut_act_retr", "prof_statut_act_foyer", "prof_statut_act_autrinac", "diplome_sans","diplome_bac", "diplome_bacplus2", "diplome_bacplus3", "age_tranche_1829","age_tranche_3039",
 "age_tranche_4049", "age_tranche_5059", "age_tranche_6069", "age_tranche_70", "vie_fam_seul", "vie_fam_coupsansenf", "vie_fam_coupenf",
 "vie_fam_mono", "vie_fam_enf", "vie_fam_autre","sexe_femme", "sexe_homme"),
	   libelle_mod = c("Agriculteur", "Artisan commerçant", "Cadre supérieur, profession libérale", "Profession intermédiaire", "Employé", "Ouvrier", "Chômeur", "Retraité",
"Au foyer", "Autre inactif", "CAP, BEP ou moins", "Baccalauréat", "Bac + 2", "Bac + 3 ou plus", "18 à 29 ans", "30 à 39 ans", "40 à 49 ans", "50 à 59 ans",
 "60 à 69 ans", "70 ans et plus", "Vit seul", "Membre du couple (pas d’enfants à charge)", "Membre du couple (enfants à charge)",
 "Chef famille monoparentale", "Enfant", "Autre situation familiale", "Femme", "Homme"),
           libelle_var=c("Situation professionnelle",rep("",9),"Niveau de diplôme le plus élevé",rep("",3), "Classe d'âge",rep("",5),"Situation familiale",rep("",5),"Sexe",rep("",1))
) ,
    by="variable")  %>% 
     arrange(match(variable,c("prof_statut_act_agri", "prof_statut_act_commer", "prof_statut_act_cadre", "prof_statut_act_inter", "prof_statut_act_employ", "prof_statut_act_ouv", "prof_statut_act_chom",
"prof_statut_act_retr", "prof_statut_act_foyer", "prof_statut_act_autrinac", "diplome_sans","diplome_bac", "diplome_bacplus2", "diplome_bacplus3", "age_tranche_1829","age_tranche_3039",
 "age_tranche_4049", "age_tranche_5059", "age_tranche_6069", "age_tranche_70", "vie_fam_seul", "vie_fam_coupsansenf", "vie_fam_coupenf",
 "vie_fam_mono", "vie_fam_enf", "vie_fam_autre","sexe_femme", "sexe_homme")))  %>% 
  dplyr::select(libelle_var,libelle_mod,pauvrete)  %>% 
  replace(is.na(.), "Réf.") %>% 
  setNames(c("","","Effet sur l'indice global de pauvreté (m+i+s)"))


# tab_covariates_global_cfa <- sum$pe %>% 
#   filter(op=="~" & substr(rhs,1,3)=="cov") %>% 
#   mutate(variable=gsub("cov_","",rhs),
#          pvaleur=cut(pvalue, breaks = c(0, 0.001, 0.01, 0.05, 1),
#                                       include.lowest = TRUE,
#                                       labels = c('***', '**', '*', '')),
#          estimateur=paste0(round(est,2),pvaleur) 
#          ) %>% arrange(desc(abs(est))) %>% 
#   dplyr::select(lhs,variable,estimateur) %>%
#   pivot_wider(
#     names_from = lhs,
#     values_from = estimateur
#   ) %>% dplyr::left_join(
#     data.frame(variable = c("prof_statut_act_agri", "prof_statut_act_commer", "prof_statut_act_cadre", "prof_statut_act_inter", "prof_statut_act_employ", "prof_statut_act_ouv", "prof_statut_act_chom",
# "prof_statut_act_retr", "prof_statut_act_foyer", "prof_statut_act_autrinac", "diplome_sans","diplome_bac", "diplome_bacplus2", "diplome_bacplus3", "age_tranche_1829","age_tranche_3039",
#  "age_tranche_4049", "age_tranche_5059", "age_tranche_6069", "age_tranche_70", "vie_fam_seul", "vie_fam_coupsansenf", "vie_fam_coupenf",
#  "vie_fam_mono", "vie_fam_enf", "vie_fam_autre","sexe_femme", "sexe_homme"),
# 	   libelle_mod = c("Agriculteur", "Artisan commerçant", "Cadre supérieur, profession libérale", "Profession intermédiaire", "Employé", "Ouvrier", "Chômeur", "Retraité",
# "Au foyer", "Autre inactif", "CAP, BEP ou moins", "Baccalauréat", "Bac + 2", "Bac + 3 ou plus", "18 à 29 ans", "30 à 39 ans", "40 à 49 ans", "50 à 59 ans",
#  "60 à 69 ans", "70 ans et plus", "Vit seul", "Membre du couple (pas d’enfants à charge)", "Membre du couple (enfants à charge)",
#  "Chef famille monoparentale", "Enfant", "Autre situation familiale", "Femme", "Homme"),
#            libelle_var=c("Situation professionnelle",rep("",9),"Niveau de diplôme le plus élevé",rep("",3), "Classe d'âge",rep("",5),"Situation familiale",rep("",5),"Sexe",rep("",1))
# ) ,
#     by="variable")  %>% 
#   dplyr::select(libelle_mod,pauvrete) %>%
#   setNames(c("","Effet sur l'indice global de pauvreté (m+i+s)"))
# 
# 
# tab_covariates_global_cfa %>%
#   kable(caption="Effets des covariables sur l'indice global de pauvreté", booktabs = TRUE, longtable = TRUE) %>%
#       kableExtra::column_spec(1:2, width = "4cm") %>%
#   kableExtra::kable_styling(
#   latex_options = c("hold_position", "repeat_header"),
#   repeat_header_text = "\\textit{(suite)}",
#   repeat_header_continued = "\\textit{(suite en page suivante...)}"
#   ) %>%
#   kableExtra::footnote("* : significatif au seuil de 5 % ; ** : 1 % ; *** : 0,1 %.")

```


```{r, include=FALSE}

pauv_model_mimic_global_new1 <- '
m =~ 0.81*m_quantilenivie_inv + m_locatif_inv + m_financier_inv
i =~ 0.75*i_rsa +  i_chom + i_log + i_handi + i_bourse + i_hlm
#s =~ 0.73*s_sentpauvrisque + s_infminidecla
#s_infminidecla ~~ m_quantilenivie_inv

#pauvrete =~ NA*m + i + s
pauvrete =~ NA*m + i


# Correction de la variance négative
m ~~ 0.04*m
pauvrete ~~ 1 * pauvrete


# Controles globaux
pauvrete ~  cov_prof_statut_act_agri + cov_prof_statut_act_commer + cov_prof_statut_act_cadre + cov_prof_statut_act_employ + cov_prof_statut_act_ouv + cov_prof_statut_act_chom + 
cov_prof_statut_act_retr +  cov_prof_statut_act_foyer +
cov_prof_statut_act_autrinac + cov_diplome_sans + cov_diplome_bacplus2 + cov_diplome_bacplus3 + cov_age_tranche_1829 + cov_age_tranche_4049 + cov_age_tranche_5059 + cov_age_tranche_6069 + cov_age_tranche_70 +
cov_vie_fam_seul + cov_vie_fam_coupenf + cov_vie_fam_mono +
cov_vie_fam_enf   + cov_vie_fam_autre +  cov_sexe_homme
'



fit_mimic_global_new1 <- lavaan::cfa(pauv_model_mimic_global_new1, data = bdd_CFA_rmnasup,ordered=TRUE)

sum_new1 <- summary(fit_mimic_global_new1, standardized = TRUE, fit.measures = TRUE)

f <- fitMeasures(fit_mimic_global_new1)[c("chisq","df","cfi","rmsea", "srmr")]
f <- c(round(f[c("chisq","df")]), gsub("\\.",",", round(f[c("cfi","rmsea", "srmr")],3)))
names(f) <- c("chisq","df","cfi","rmsea", "srmr")
```

```{r, echo=FALSE, eval = TRUE}


tab_covariates_global_cfa_new1 <- sum_new1$pe %>% 
  filter(op=="~" & substr(rhs,1,3)=="cov") %>% 
  mutate(variable=gsub("cov_","",rhs),
         pvaleur=cut(pvalue, breaks = c(0, 0.001, 0.01, 0.05, 1),
                                      include.lowest = TRUE,
                                      labels = c('***', '**', '*', '')),
         estimateur=paste0(round(est,2),pvaleur) 
         ) %>% 
  dplyr::select(lhs,variable,estimateur) %>%
  pivot_wider(
    names_from = lhs,
    values_from = estimateur
  ) %>% dplyr::right_join(
    data.frame(variable = c("prof_statut_act_agri", "prof_statut_act_commer", "prof_statut_act_cadre", "prof_statut_act_inter", "prof_statut_act_employ", "prof_statut_act_ouv", "prof_statut_act_chom",
"prof_statut_act_retr", "prof_statut_act_foyer", "prof_statut_act_autrinac", "diplome_sans","diplome_bac", "diplome_bacplus2", "diplome_bacplus3", "age_tranche_1829","age_tranche_3039",
 "age_tranche_4049", "age_tranche_5059", "age_tranche_6069", "age_tranche_70", "vie_fam_seul", "vie_fam_coupsansenf", "vie_fam_coupenf",
 "vie_fam_mono", "vie_fam_enf", "vie_fam_autre","sexe_femme", "sexe_homme"),
	   libelle_mod = c("Agriculteur", "Artisan commerçant", "Cadre supérieur, profession libérale", "Profession intermédiaire", "Employé", "Ouvrier", "Chômeur", "Retraité",
"Au foyer", "Autre inactif", "CAP, BEP ou moins", "Baccalauréat", "Bac + 2", "Bac + 3 ou plus", "18 à 29 ans", "30 à 39 ans", "40 à 49 ans", "50 à 59 ans",
 "60 à 69 ans", "70 ans et plus", "Vit seul", "Membre du couple (pas d’enfants à charge)", "Membre du couple (enfants à charge)",
 "Chef famille monoparentale", "Enfant", "Autre situation familiale", "Femme", "Homme"),
           libelle_var=c("Situation professionnelle",rep("",9),"Niveau de diplôme le plus élevé",rep("",3), "Classe d'âge",rep("",5),"Situation familiale",rep("",5),"Sexe",rep("",1))
) ,
    by="variable")  %>% 
     arrange(match(variable,c("prof_statut_act_agri", "prof_statut_act_commer", "prof_statut_act_cadre", "prof_statut_act_inter", "prof_statut_act_employ", "prof_statut_act_ouv", "prof_statut_act_chom",
"prof_statut_act_retr", "prof_statut_act_foyer", "prof_statut_act_autrinac", "diplome_sans","diplome_bac", "diplome_bacplus2", "diplome_bacplus3", "age_tranche_1829","age_tranche_3039",
 "age_tranche_4049", "age_tranche_5059", "age_tranche_6069", "age_tranche_70", "vie_fam_seul", "vie_fam_coupsansenf", "vie_fam_coupenf",
 "vie_fam_mono", "vie_fam_enf", "vie_fam_autre","sexe_femme", "sexe_homme")))  %>% 
  dplyr::select(libelle_var,libelle_mod,pauvrete)  %>% 
  replace(is.na(.), "Réf.") %>% 
  setNames(c("","","Effet sur l'indice global de pauvreté (m+i)"))
 
```

```{r, include=FALSE}

pauv_model_mimic_global_new2 <- '
#m =~ 0.81*m_quantilenivie_inv + m_locatif_inv + m_financier_inv
pauvrete =~ 0.81*m_quantilenivie_inv + m_locatif_inv + m_financier_inv
#i =~ 0.75*i_rsa +  i_chom + i_log + i_handi + i_bourse + i_hlm
#s =~ 0.73*s_sentpauvrisque + s_infminidecla
#s_infminidecla ~~ m_quantilenivie_inv
#pauvrete =~ NA*m + i


# Correction de la variance négative
#m ~~ 0.04*m
pauvrete ~~ 1 * pauvrete


# Controles globaux
pauvrete ~  cov_prof_statut_act_agri + cov_prof_statut_act_commer + cov_prof_statut_act_cadre + cov_prof_statut_act_employ + cov_prof_statut_act_ouv + cov_prof_statut_act_chom + 
cov_prof_statut_act_retr +  cov_prof_statut_act_foyer +
cov_prof_statut_act_autrinac + cov_diplome_sans + cov_diplome_bacplus2 + cov_diplome_bacplus3 + cov_age_tranche_1829 + cov_age_tranche_4049 + cov_age_tranche_5059 + cov_age_tranche_6069 + cov_age_tranche_70 +
cov_vie_fam_seul + cov_vie_fam_coupenf + cov_vie_fam_mono +
cov_vie_fam_enf   + cov_vie_fam_autre +  cov_sexe_homme
'



fit_mimic_global_new2 <- lavaan::cfa(pauv_model_mimic_global_new2, data = bdd_CFA_rmnasup,ordered=TRUE)

f <- fitMeasures(fit_mimic_global_new2)[c("chisq","df","cfi","rmsea", "srmr")]
f <- c(round(f[c("chisq","df")]), gsub("\\.",",", round(f[c("cfi","rmsea", "srmr")],3)))
names(f) <- c("chisq","df","cfi","rmsea", "srmr")

sum_new2 <- summary(fit_mimic_global_new2, standardized = TRUE, fit.measures = TRUE)
```

```{r, echo=FALSE, eval = TRUE}


tab_covariates_global_cfa_new2 <- sum_new2$pe %>% 
  filter(op=="~" & substr(rhs,1,3)=="cov") %>% 
  mutate(variable=gsub("cov_","",rhs),
         pvaleur=cut(pvalue, breaks = c(0, 0.001, 0.01, 0.05, 1),
                                      include.lowest = TRUE,
                                      labels = c('***', '**', '*', '')),
         estimateur=paste0(round(est,2),pvaleur) 
         ) %>% 
  dplyr::select(lhs,variable,estimateur) %>%
  pivot_wider(
    names_from = lhs,
    values_from = estimateur
  ) %>% dplyr::right_join(
    data.frame(variable = c("prof_statut_act_agri", "prof_statut_act_commer", "prof_statut_act_cadre", "prof_statut_act_inter", "prof_statut_act_employ", "prof_statut_act_ouv", "prof_statut_act_chom",
"prof_statut_act_retr", "prof_statut_act_foyer", "prof_statut_act_autrinac", "diplome_sans","diplome_bac", "diplome_bacplus2", "diplome_bacplus3", "age_tranche_1829","age_tranche_3039",
 "age_tranche_4049", "age_tranche_5059", "age_tranche_6069", "age_tranche_70", "vie_fam_seul", "vie_fam_coupsansenf", "vie_fam_coupenf",
 "vie_fam_mono", "vie_fam_enf", "vie_fam_autre","sexe_femme", "sexe_homme"),
	   libelle_mod = c("Agriculteur", "Artisan commerçant", "Cadre supérieur, profession libérale", "Profession intermédiaire", "Employé", "Ouvrier", "Chômeur", "Retraité",
"Au foyer", "Autre inactif", "CAP, BEP ou moins", "Baccalauréat", "Bac + 2", "Bac + 3 ou plus", "18 à 29 ans", "30 à 39 ans", "40 à 49 ans", "50 à 59 ans",
 "60 à 69 ans", "70 ans et plus", "Vit seul", "Membre du couple (pas d’enfants à charge)", "Membre du couple (enfants à charge)",
 "Chef famille monoparentale", "Enfant", "Autre situation familiale", "Femme", "Homme"),
           libelle_var=c("Situation professionnelle",rep("",9),"Niveau de diplôme le plus élevé",rep("",3), "Classe d'âge",rep("",5),"Situation familiale",rep("",5),"Sexe",rep("",1))
) ,
    by="variable")  %>% 
     arrange(match(variable,c("prof_statut_act_agri", "prof_statut_act_commer", "prof_statut_act_cadre", "prof_statut_act_inter", "prof_statut_act_employ", "prof_statut_act_ouv", "prof_statut_act_chom",
"prof_statut_act_retr", "prof_statut_act_foyer", "prof_statut_act_autrinac", "diplome_sans","diplome_bac", "diplome_bacplus2", "diplome_bacplus3", "age_tranche_1829","age_tranche_3039",
 "age_tranche_4049", "age_tranche_5059", "age_tranche_6069", "age_tranche_70", "vie_fam_seul", "vie_fam_coupsansenf", "vie_fam_coupenf",
 "vie_fam_mono", "vie_fam_enf", "vie_fam_autre","sexe_femme", "sexe_homme")))  %>% 
  dplyr::select(libelle_var,libelle_mod,pauvrete)  %>% 
  replace(is.na(.), "Réf.") %>% 
  setNames(c("","","Effet sur l'indice global de pauvreté (m)"))
```

```{r, echo=FALSE, eval = TRUE}

tab_covariates_global_cfa_final <- cbind(
  tab_covariates_global_cfa_new2,
  tab_covariates_global_cfa_new1[,3],
  tab_covariates_global_cfa[,3]
      )

tab_covariates_global_cfa_final %>%
  setNames(c("","Pauvreté...", "Monétaire", "Mon. + Institutio.", "Mon. + Institutio. + subjective")) %>% 
  kable(
    #caption="Effets des covariables sur la pauveté",
        booktabs = TRUE,
        longtable = FALSE #TRUE bug !!
        ) %>%
      kableExtra::column_spec(1:2, width = "4cm") %>%
      kableExtra::column_spec(3:5, width = "2cm") %>%
  kableExtra::kable_styling(
  latex_options = c("hold_position", "repeat_header"),
  repeat_header_text = "\\textit{(suite)}",
  repeat_header_continued = "\\textit{(suite en page suivante...)}"
  ) %>%
  kableExtra::footnote("* : significatif au seuil de 5 % ; ** : 1 % ; *** : 0,1 %.")

```



\newpage 
\newpage

# Tableau encadré 2

```{r, echo=FALSE}

tab_modfit_afc <- readRDS("../rapport/figures/tab_modfit_afc.RDS") 

f2 <- fitMeasures(fit2_var)
tab_modfit_afc[3,2:6] <- c(round(f2[c("chisq","df")]), gsub("\\.",",", round(f2[c("cfi","rmsea", "srmr")],3)))
f3 <- fitMeasures(fit_hier3_var)
tab_modfit_afc[4,2:6] <- c(round(f3[c("chisq","df")]), gsub("\\.",",", round(f3[c("cfi","rmsea", "srmr")],3)))

tab_modfit_afc %>%
  kable(#caption="Indices d'ajustement des 4 modèles d'AFC"
        )

```



